# TSSS(Think Straight, Stop Smart) 기반 Multi-Hop RAG System

In [6]:
!pip install -qU langchain langchain-openai langchain-huggingface langchain-chroma sentence-transformers scikit-learn langsmith langchain-google-genai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.9/107.9 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 89.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.0/283.0 kB 25.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 60.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 718.4/718.4 kB 55.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 29.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.9/234.9 kB 26.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 82.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.4/17.4 MB 80.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.0/220.0 kB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.4/128.4 kB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.43.0, but you have google-auth 2.47.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.37.0 requires opentelemetry-exporter-otlp-proto-common==1.37.0, but you have opentelemetry-exporter-otlp-proto-common 1.39.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.37.0 requires opentelemetry-proto==1.37.0, but you have opentelemetry-proto 1.39.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.37.0 requires opentelemetry-sdk~=1.37.0, but you have opentelemetry-sdk 1.39.1 which is incompatible.
google-adk 1.21.0 requires opentelemetry-api<=1.37.0,>=1.37.0, but you have opentelemetry-api 1.39.1 which is incompatible.
google-adk 1.21.0 requires opentelemetry-sdk<=1.37.0,>=1.37.0, but you have opentelemetry-sdk 1.39.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.39.1 which is incompatible.

In [7]:
import os
import torch
from google.colab import drive, userdata


# 1. 구글 드라이브 마운트 (데이터가 드라이브에 있으므로 필수)
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. LangSmith 환경 변수 설정
os.environ["LANGCHAIN_API_KEY"] = userdata.get('langgrpah')
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_PROJECT"] = "TSSS" # 프로젝트 이름 (원하는대로 변경 가능)

print("\nLangSmith 설정 및 드라이브 마운트 완료!")

LangSmith 설정 및 드라이브 마운트 완료!

In [8]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

# 설정된 경로 (사용자님 경로)
BASE_PATH = "/content/drive/MyDrive/chroma_db_bge_m3"

# 임베딩 모델 로드
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Loading Embedding Model on {device}...")

embedding_model = HuggingFaceEmbeddings(
    model_name="BAAI/bge-m3",
    model_kwargs={"device": device},
    encode_kwargs={"normalize_embeddings": True}
)

# 실제 DB 파일(chroma.sqlite3)이 있는 경로 찾기
# (압축 풀면서 폴더가 중첩되었을 경우를 대비한 사용자님의 기존 로직)
real_db_path = BASE_PATH
for root, dirs, files in os.walk(BASE_PATH):
    if "chroma.sqlite3" in files:
        real_db_path = root
        print(f"실제 DB 파일 발견 경로: {real_db_path}")
        break

# ChromaDB 로드
# 중요: collection_name을 꼭 명시해야 데이터가 보입니다!
vectorstore = Chroma(
    persist_directory=real_db_path,
    embedding_function=embedding_model,
    collection_name="multihop_rag"  # 기존 코드에 있던 컬렉션 이름
)

# 연결 확인
count = vectorstore._collection.count()
print(f"\n로드된 문서 개수: {count}개")

if count > 0:
    # 테스트 검색 (LangSmith에 기록되는지 확인용)
    test_retriever = vectorstore.as_retriever(search_kwargs={"k": 1})
    docs = test_retriever.invoke("테스트 검색")
    print(f"테스트 검색 결과: {docs[0].page_content[:50]}...")
else:
    print("여전히 데이터가 0개입니다. 경로 내의 'collection_name'이 맞는지 확인이 필요합니다.")

Loading Embedding Model on cuda...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

실제 DB 파일 발견 경로: /content/drive/MyDrive/chroma_db_bge_m3

로드된 문서 개수: 2157개
테스트 검색 결과: Title: Is Google Search better than the rest? And ...

In [10]:
import os
import torch
import json
import re
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive, userdata
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langsmith import traceable
from langchain_openai import ChatOpenAI

# Mdel Selection
# [Option A] OpenAI (Default)
# from langchain_openai import ChatOpenAI
# if "OPENAI_API_KEY" not in os.environ:
#     os.environ["OPENAI_API_KEY"] = userdata.get('openai')
# llm = ChatOpenAI(model="gpt-4o-mini", temperature=0, seed=2026)
# print("LLM Selected: OpenAI (GPT-4o-mini)")

# [Option B] Google Gemini
# from langchain_google_genai import ChatGoogleGenerativeAI
# if "GOOGLE_API_KEY" not in os.environ:
#     os.environ["GOOGLE_API_KEY"] = userdata.get('gemini') # Secrets 이름 확인
# llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0,, seed=2026)
# print("LLM Selected: Google Gemini (1.5 Flash)")

# [Option C] OpenRouter (DeepSeek, Claude, Llama etc.)
# from langchain_openai import ChatOpenAI
# if "OPENROUTER_API_KEY" not in os.environ:
#     os.environ["OPENROUTER_API_KEY"] = userdata.get('openrouter') # Secrets 이름 확인
# llm = ChatOpenAI(
#     base_url="https://openrouter.ai/api/v1",
#     api_key=os.environ["openrouter"],
#     model="openai/gpt-oss-120b:free", # 원하는 모델명으로 변경 가능
#     temperature=0,
#     seed=2026
# )
llm = ChatOpenAI(
        model="openai/gpt-oss-120b:free",
        openai_api_key=userdata.get('openrouter'),
        openai_api_base="https://openrouter.ai/api/v1",
        temperature=0, # 사실 기반 답변
        seed=2026,
        default_headers={
            "HTTP-Referer": "https://colab.research.google.com",
            "X-Title": "MULTI HOP RAG Project"
        }
    )
print("LLM Selected: OpenRouter")

LLM Selected: OpenRouter

In [11]:
# @title TSSS (Think Straight, Stop Smart) 핵심 로직
# [핵심 기능] Stop Smart: 쿼리 유사도 계산기
def calculate_similarity(query1, query2):
    # BGE-M3로 임베딩 (GPU 사용)
    emb1 = embedding_model.embed_query(query1)
    emb2 = embedding_model.embed_query(query2)
    # 코사인 유사도 계산
    return cosine_similarity([emb1], [emb2])[0][0]

# [핵심 기능] Think Straight: 논문 Appendix B 프롬프트 생성기
def generate_tsss_prompt(main_question, history_facts):
    prompt = f"To answer the Main Question ({{ {main_question} }}), "
    if history_facts:
        prompt += "using the following facts:\n"
        for fact in history_facts:
            prompt += f"- {{ {fact} }}\n"
    prompt += "\nI propose the following additional question:\nQuestion: "
    return prompt

def extract_verbatim_evidence(query, context):
    """
    LLM에게 요약을 금지하고, 근거가 되는 '원본 문장'을 그대로 발췌하게 함
    """
    prompt = f"""
    Task: Identify the SINGLE sentence in the [Context] that acts as the core evidence for the [Query].

    [Rules]
    1. Output ONLY the raw sentence from the text.
    2. DO NOT paraphrase, summarize, or edit. Copy-paste exactly.
    3. If the answer is not in the text, output "IRRELEVANT".

    [Query]: {query}
    [Context]: {context}

    Extracted Sentence:
    """
    # 팩트 추출용 LLM 호출
    fact = llm.invoke([HumanMessage(content=prompt)]).content.strip().replace('"', '')
    return fact

def refine_answer_minimalist(question, raw_answer):
    """
    Without asking complex questions, you'll understand the LLM's intent on your own, transforming you into a police officer who best understands the situation.
    """
    prompt = f"""
    Task: Reduce the [Raw Answer] to the absolute minimum logical unit required by the [Question].

    [Guiding Principle]
    1. **Binary Choice:** Output ONLY "Yes" or "No".
    2. **Timing:** Output ONLY the time clause (e.g., "Before", "After 2023").
    3. **Entity:** Output ONLY the name/entity.
    4. **Unknowable:** If the [Raw Answer] indicates the information is missing or cannot be deduced, output EXACTLY "Insufficient information".
    5. **Formatting:** DROP ALL explanations, articles, and punctuation.

    [Input]
    Question: {question}
    Raw Answer: {raw_answer}

    Minimalist Answer:
    """

    # LLM이 스스로 판단해서 최적의 단어를 선택함
    refined = llm.invoke([HumanMessage(content=prompt)]).content.strip()

    # 혹시 모를 마침표 제거
    return refined.rstrip(".")

def check_new_terms_detected(query1, query2):
    """
    하드코딩된 정규식(대문자 체크)을 제거하고,
    단순 집합(Set) 연산으로 '새로운 의미 있는 단어'가 추가되었는지 감지합니다.
    (영어, 한국어 모두 작동)
    """
    if not query2: return True

    # 1. 전처리: 특수문자 제거 및 소문자화 (언어 중립성 확보)
    def tokenize(text):
        # 글자, 숫자, 한글 등을 제외한 특수문자는 공백으로 치환
        clean_text = re.sub(r'[^\w\s]', ' ', text).lower()
        return set(clean_text.split())

    tokens_new = tokenize(query1)
    tokens_old = tokenize(query2)

    # 2. 불용어(Stopwords) 처리 (선택 사항: 간단한 것만 제외)
    # 문법적 요소(is, the, 은, 는, 이, 가)가 아닌 '실질적 단어' 차이만 봅니다.
    # 여기서는 간단히 길이 2 이상의 단어만 체크합니다.
    diff = {w for w in (tokens_new - tokens_old) if len(w) > 1}

    if diff:
        print(f"    -> [Override] New Terms Detected: {diff}. Ignoring similarity stop.")
        return True
    return False

In [12]:
# @title 최종 retrieval
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

@traceable(name="TSSS_Final_Semantic")
def run_tsss_semantic_dedup(question, max_steps=5, threshold=0.85, top_k=5):
    print(f"\n[Processing TSSS Semantic]: {question}\n")

    history_facts = []
    past_queries = []
    evidence_list = []

    # 수집된 팩트들의 임베딩을 저장할 리스트 (비교용)
    collected_embeddings = []

    for step in range(max_steps):
        # 쿼리 생성
        prompt_text = generate_tsss_prompt(question, history_facts)
        next_query = llm.invoke([HumanMessage(content=prompt_text)]).content.strip()
        next_query = next_query.replace('"', '').replace("Question:", "").strip()

        print(f"  [Step {step+1}] Query: {next_query}")

        # 종료 조건
        if "STOP" in next_query or len(next_query) < 2:
            print("    -> LLM Stop Signal.")
            break

        is_repetitive = False
        if past_queries:
            last_query = past_queries[-1]
            sim_score = calculate_similarity(next_query, last_query)
            if sim_score > threshold:
                if check_new_terms_detected(next_query, last_query):
                    is_repetitive = False
                else:
                    print(f"    -> Loop Detected (Sim: {sim_score:.2f}). Stopping.")
                    is_repetitive = True
        if is_repetitive: break
        past_queries.append(next_query)

        # 검색
        try:
            retriever = vectorstore.as_retriever(search_kwargs={"k": top_k})
            retrieved_docs = retriever.invoke(next_query)

            if not retrieved_docs:
                print("    -> No docs found.")
                continue

            found_valid = False
            for doc in retrieved_docs:
                verbatim_fact = extract_verbatim_evidence(next_query, doc.page_content)
                if "IRRELEVANT" in verbatim_fact: continue


                # 의미 기반 중복 제거 (Semantic Deduplication)

                # 현재 찾은 팩트를 벡터로 변환
                current_emb = embedding_model.embed_query(verbatim_fact)

                is_duplicate = False

                # 기존 수집된 팩트들과 의미 유사도 비교
                if collected_embeddings:
                    # 전체 리스트와 한번에 비교 (효율적)
                    sims = cosine_similarity([current_emb], collected_embeddings)[0]
                    max_sim = np.max(sims) # 가장 비슷한 문장과의 점수

                    if max_sim > 0.90: # 90% 이상 의미가 같으면 중복 처리
                        print(f"    -> [Skip] Semantically identical content detected (Sim: {max_sim:.2f}).")
                        is_duplicate = True

                if is_duplicate:
                    continue # 다음 문서 확인
                # ---------------------------------------------------------

                source_name = doc.metadata.get('source', 'Unknown')
                print(f"    -> Found New Fact in: {source_name}")
                found_valid = True

                history_facts.append(f"Source [{source_name}]: {verbatim_fact}")

                # 임베딩 저장 (다음 비교를 위해)
                collected_embeddings.append(current_emb)

                doc_meta = doc.metadata
                evidence_list.append({
                    "author": doc_meta.get("author", "unknown"),
                    "category": doc_meta.get("category", "unknown"),
                    "fact": verbatim_fact,
                    "published_at": doc_meta.get("published_at", "unknown"),
                    "source": source_name,
                    "title": doc_meta.get("original_title", "No Title"),
                    "url": doc_meta.get("url", "")
                })
                break

            if not found_valid:
                print("    -> Docs retrieved but content irrelevant or duplicated.")

        except Exception as e:
            print(f"    -> Error: {e}")
            break

    # 최종 결과 생성 및 후처리
    print("\n[Finalizing]...")
    if not history_facts:
        final_answer = "Insufficient information" # 찾은 팩트가 아예 없으면
    else:
        final_context = "\n".join(history_facts)

        # 서술형 답변 생성
        final_prompt = f"Question: {question}\nFacts: {final_context}\nAnswer:"
        raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()

        # 단답형 정제 (여기서 'Insufficient information'이 튀어나올 수 있음)
        final_answer = refine_answer_minimalist(question, raw_answer)

    # 추론 불가면 빈값 반환
    if final_answer == "Insufficient information":
        evidence_list = []  # 리스트 강제 초기화
        print("    -> Result: Insufficient info. Cleared evidence list.")

    return {
        "answer": final_answer,
        "evidence_list": evidence_list
    }

In [ ]:
# @title 실행 테스트 코드
test_q = "Does the TechCrunch article on Twitch's subscription revenue split policy indicate a different monetization strategy compared to the TechCrunch article on Beeper's plans for Beeper Mini subscriptions?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Does the TechCrunch article on Twitch's subscription revenue split policy indicate a different monetization strategy compared to the TechCrunch article on Beeper's plans for Beeper Mini subscriptions?

  [Step 1] Query: What are the key differences in the monetization strategies outlined in the TechCrunch articles for Twitch's subscription revenue split policy and Beeper's plans for Beeper Mini subscriptions?
    -> Found New Fact in: TechCrunch
  [Step 2] Query: What are the key differences in monetization strategies between Twitch's new subscription revenue split policy and Beeper's approach to its Mini subscriptions?
    -> [Override] New Terms Detected: {'new', 'approach', 'to', 'its', 'between'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 3] Query: What are the key differences in monetization strategies between Twitch's subscription revenue split policy and Beeper's plans for Beeper Mini subscriptions?
    -> [Override] New Terms Detected: {'plans', 'for'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 4] Query: How do the subscription pricing strategies of Twitch and Beeper reflect their respective business models and target audiences?
    -> [Override] New Terms Detected: {'target', 'audiences', 'reflect', 'their', 'how', 'respective', 'do', 'pricing', 'of', 'business', 'models'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 5] Query: How do the subscription revenue models of Twitch and Beeper reflect their respective approaches to monetization and creator support?
    -> [Override] New Terms Detected: {'revenue', 'support', 'to', 'creator', 'approaches', 'monetization'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Docs retrieved but content irrelevant or duplicated.

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Yes",
  "evidence_list": [
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "Last year, the company announced that it would end the 70/30 subscription revenue split deal that it had offered select streamers in favor of prioritizing ad revenue.",
      "published_at": "2023-10-26 22:28:10.000000000Z",
      "source": "TechCrunch",
      "title": "Twitch’s money guy talks about the revenue split controversy and its monetization long game",
      "url": "https://techcrunch.com/2023/10/26/twitch-mike-minton-chief-monetization-officer-twitchcon-2023-partner-plus-revenue-split/"
    },
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "The default sub (subscription) revenue split for Partners is 50/50, but select streamers were offered a premium 70/30 deal until last year.",
      "published_at": "2023-09-30 00:13:12.000000000Z",
      "source": "TechCrunch",
      "title": "Kick streamers consider leaving over CEO’s comments in a sex worker ‘prank’ stream",
      "url": "https://techcrunch.com/2023/09/29/kick-streamers-leave-ceo-ice-poseidon-prank-sex-work/"
    },
    {
      "author": "Sarah Perez",
      "category": "technology",
      "fact": "Beeper Mini is competitively priced at $1.99 per month, with a seven-day free trial, compared with $15 per month for the recently acquired competitor Texts.com bought by Automattic.",
      "published_at": "2023-12-05 15:00:57.000000000Z",
      "source": "TechCrunch",
      "title": "Beeper reversed engineered iMessage to bring blue bubble texts to Android users",
      "url": "https://techcrunch.com/2023/12/05/beeper-reversed-engineered-imessage-to-bring-blue-bubble-texts-to-android-users/"
    },
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "One thing we’ve done since the beginning, where we are a leader, is getting people to take their wallets out and support creators through subscriptions, gifting, cheering.",
      "published_at": "2023-10-26 22:28:10.000000000Z",
      "source": "TechCrunch",
      "title": "Twitch’s money guy talks about the revenue split controversy and its monetization long game",
      "url": "https://techcrunch.com/2023/10/26/twitch-mike-minton-chief-monetization-officer-twitchcon-2023-partner-plus-revenue-split/"
    }
  ]
}

## 평가

In [13]:
# @title dataset load
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from datasets import load_dataset

# QA 데이터셋 로드
try:
    qa_df
except NameError:
    print("QA 데이터셋 로드 중...")
    ds = load_dataset("yixuantt/MultiHopRAG", "MultiHopRAG", split="train")
    qa_df = ds.to_pandas()

# 층화 추출 (Stratified Sampling) - 비율 맞춰서 50개 뽑기
print(f"전체 데이터 개수: {len(qa_df)}")
print("Question Type별 비율에 맞춰 50개 샘플링 중...")

# sklearn을 사용하여 비율 유지하며 추출
sampled_df, _ = train_test_split(
    qa_df,
    train_size=50,
    stratify=qa_df['question_type'],
    random_state=42 # 재현성을 위해 시드 고정
)

print(f"추출된 샘플 개수: {len(sampled_df)}")
print(sampled_df['question_type'].value_counts()) # 타입별 개수 확인

QA 데이터셋 로드 중...

README.md: 0.00B [00:00, ?B/s]

MultiHopRAG.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/2556 [00:00<?, ? examples/s]

전체 데이터 개수: 2556
Question Type별 비율에 맞춰 50개 샘플링 중...
추출된 샘플 개수: 50
question_type
comparison_query    17
inference_query     16
temporal_query      11
null_query           6
Name: count, dtype: int64

In [14]:
# @title 평가 실행 (RAG Inference)
rag_answers = []
rag_evidence_lists = []

print("\n=== RAG 평가 데이터 생성 시작 (총 50개) ===")
# tqdm으로 진행 상황 바 표시
for index, row in tqdm(sampled_df.iterrows(), total=len(sampled_df), desc="Processing Queries"):
    query = row['query']

    try:
        # 기존에 만드신 함수 호출 (top_k=5 적용)
        # LangSmith 추적도 자동으로 됩니다.
        result = run_tsss_semantic_dedup(query, top_k=5)

        rag_answers.append(result['answer'])
        rag_evidence_lists.append(result['evidence_list'])

    except Exception as e:
        print(f"Error at index {index}: {e}")
        rag_answers.append("Error")
        rag_evidence_lists.append([])

# 결과 저장 및 컬럼 정리
# 원본 데이터프레임에 RAG 결과 추가
sampled_df['RAG_answer'] = rag_answers
sampled_df['RAG_evidence_list'] = rag_evidence_lists

# 요청하신 컬럼 순서대로 정리
# (데이터셋의 컬럼명이 'query', 'answer', 'evidence_list' 라고 가정)
final_eval_df = sampled_df[[
    "query",
    "evidence_list",
    "RAG_evidence_list",
    "answer",
    "RAG_answer"
]].copy()

# 5. 결과 확인 및 저장
print("\n=== 생성 완료 ===")
display(final_eval_df.head(3)) # 상위 3개 미리보기

# CSV로 저장 (필요 시)
# final_eval_df.to_csv("/content/drive/MyDrive/MultihopRAG/rag_evaluation_results.csv", index=False, encoding="utf-8-sig")
# print("결과가 'rag_evaluation_results.csv'로 저장되었습니다.")

=== RAG 평가 데이터 생성 시작 (총 50개) ===

Processing Queries:   0%|          | 0/50 [00:00<?, ?it/s]

[Processing TSSS Semantic]: Does the TechCrunch article suggest that "People's preferences regarding social media content" will shift towards uncurated experiences, while The Roar | Sports Writers Blog indicates that "Michael Cheika" values past experiences, curated or not, for preparation?

  [Step 1] Query: **Proposed additional question**

*How do the TechCrunch article’s observations about a growing user preference for uncurated, “raw” social‑media experiences compare with The Roar’s description of Michael Cheika’s attitude toward past experiences—whether curated or not—as a source of preparation and insight?*
    -> Found New Fact in: TechCrunch
  [Step 2] Query: **Answer to the Main Question**

- **TechCrunch:** The excerpt you provided (“…after everything on social media becomes so perfectly curated for us, our brains will start to crave things that are not”) clearly indicates that the author believes people’s preferences will move **away** from highly‑curated social‑media feeds toward **more uncurated, raw experiences**.

- **The Roar | Sports Writers Blog:** No excerpt or citation has been supplied that shows what Michael Cheika says about past experiences—curated or not—and how they factor into his preparation. Because we lack that source, we cannot confirm whether the blog states that Cheika “values past experiences, curated or not, for preparation.”

**Bottom line:** The TechCrunch article does suggest a shift toward uncurated content, but we do not have enough evidence from *The Roar* to verify the claim about Michael Cheika.

---

### Suggested Additional Question

> *What specific statements does Michael Cheika make in the “The Roar | Sports Writers Blog” article about the role of past experiences (whether curated or uncurated) in his preparation for coaching or competition?*

This question would help obtain the missing evidence needed to answer the second half of the main question definitively.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: The Roar | Sports Writers Blog
  [Step 3] Query: **Answer to the Main Question**

- **TechCrunch:** The article states, *“He also believes that after everything on social media becomes so perfectly curated for us, our brains will start to crave things that are not.”* This directly indicates that the author expects people’s preferences to move **away from highly curated content toward more uncurated, raw experiences** on social media【TechCrunch】.

- **The Roar | Sports Writers Blog:** The passage notes, *“What we have done since then, all the success and failures [matters in our preparation].”* In the context of Michael Cheika’s comments, this means he **values all past experiences—whether they were successes, failures, curated, or uncurated—as material for preparation**【The Roar】.

**Therefore, the answer is: Yes.** The TechCrunch piece predicts a shift toward uncurated social‑media content, while the Roar article shows that Michael Cheika draws on his entire history of experiences (curated or not) when preparing.

---

### Suggested Additional Question

> **How might the growing appetite for uncurated content influence the way brands and athletes (like Michael Cheika) communicate with their audiences?**

This follow‑up invites exploration of the practical implications of the two trends identified above.
    -> [Override] New Terms Detected: {'like', 'two', 'influence', 'above', 'entire', 'matters', 'history', 'then', 'trends', 'done', 'expects', 'exploration', 'practical', 'appetite', 'since', 'when', 'athletes', 'way', 'is', 'invites', 'might', 'identified', 'passage', 'communicate', 'with', 'growing', 'success', 'failures', 'all', 'material', 'implications', 'up', 'were', 'preparing', 'means', 'comments', 'piece', 'draws', 'also', 'successes', 'follow', 'while', 'as', 'audiences', 'therefore', 'yes', 'their', 'predicts', 'notes', 'context', 'brands', 'directly', 'he'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 0.96).
    -> Found New Fact in: TechCrunch
  [Step 4] Query: **Answer**

Yes.

**Why the TechCrunch article supports the first part**

- The TechCrunch quote says: *“after everything on social media becomes so perfectly curated for us, our brains will start to crave things that are not.”*
- This directly states that, once social‑media feeds are overly polished, people’s preferences will move toward **uncurated, raw content**.

**Why The Roar | Sports Writers Blog supports the second part**

- The Roar quote reads: *“What we have done since then, all the success and failures … matters in our preparation.”*
- By emphasizing that **both successes and failures** (i.e., all past experiences, whether they were the result of careful curation or not) are important for preparation, the article indicates that **Michael Cheika values past experiences in general**, not just curated ones.

**Conclusion**

- The TechCrunch piece predicts a shift in audience taste toward uncurated social‑media experiences.
- The Roar article shows that Michael Cheika draws on the totality of his past—curated or uncurated—to prepare for future challenges.

(The third TechCrunch fact about federal regulation is unrelated to these points.)
    -> [Override] New Terms Detected: {'just', 'conclusion', 'curation', 'reads', 'prepare', 'general', 'why', 'points', 'says', 'ones', 'unrelated', 'emphasizing', 'totality', 'by', 'challenges', 'regulation', 'these', 'polished', 'first', 'audience', 'feeds', 'taste', 'federal', 'quote', 'result', 'fact', 'overly', 'important', 'careful', 'part', 'second', 'supports', 'once', 'third', 'both', 'future', 'about'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Docs retrieved but content irrelevant or duplicated.
  [Step 5] Query: **Answer to the Main Question**

- **TechCrunch:** The article states that “after everything on social media becomes so perfectly curated for us, our brains will start to crave things that are not.” This directly indicates that the author expects **people’s preferences to shift away from highly curated content toward more uncurated, raw experiences**.

- **The Roar | Sports Writers Blog:** The passage notes that “what we have done since then, all the success and failures … matters in our preparation.” In the context of Michael Cheika’s comments, this means he **values the totality of past experiences—both curated successes and uncurated failures—as material for preparation**. The wording “curated or not” is implied by the inclusion of “failures,” which are typically less polished.

**Conclusion:** Yes. The TechCrunch piece predicts a move toward uncurated social‑media content, while the Roar article shows that Michael Cheika draws on all past experiences, regardless of how polished they were, when preparing for future challenges.

---

### Suggested Additional Question

> **How might brands and sports teams adjust their communication strategies if audiences increasingly prefer uncurated content and leaders like Michael Cheika emphasize learning from both successes and failures?**
    -> [Override] New Terms Detected: {'wording', 'like', 'inclusion', 'communication', 'more', 'emphasize', 'leaders', 'away', 'which', 'expects', 'less', 'when', 'might', 'if', 'passage', 'strategies', 'implied', 'question', 'material', 'teams', 'typically', 'from', 'preparing', 'means', 'comments', 'learning', 'while', 'as', 'audiences', 'regardless', 'their', 'suggested', 'adjust', 'author', 'increasingly', 'how', 'highly', 'notes', 'main', 'context', 'prefer', 'brands', 'he', 'additional'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Docs retrieved but content irrelevant or duplicated.

[Finalizing]...

Processing Queries:   2%|▏         | 1/50 [02:30<2:03:13, 150.89s/it]

[Processing TSSS Semantic]: Who is the individual targeted by Attorney General Letitia James for penalties and a business ban in New York, who also allegedly inflated the value of his Manhattan apartment, as reported by both Fortune and The Age, to conceal the diminished valuation of another one of his properties?

  [Step 1] Query: The person in question is **Michele S. Miller**.
    -> Docs retrieved but content irrelevant or duplicated.
  [Step 2] Query: **Proposed additional question**

*What is the name of the New York real‑estate developer or businessman that Attorney General Letitia James is seeking penalties and a business‑activity ban against, and who has been accused—by both Fortune and The Age—of inflating the reported value of his Manhattan apartment to hide the reduced valuation of another property?*
    -> Found New Fact in: Fortune
  [Step 3] Query: **Proposed additional question**

*What is the name of the former U.S. president who is being sued by New York Attorney General Letitia James for penalties and a business‑entity ban, and who is also accused of inflating the value of his Manhattan penthouse to hide the lower valuation of another property?*
    -> [Override] New Terms Detected: {'being', 'president', 'lower', 'entity', 'sued', 'also', 'penthouse', 'former', 'for'}. Ignoring similarity stop.
    -> Found New Fact in: Fortune
  [Step 4] Query: The individual is former President **Donald Trump**.
    -> Found New Fact in: The Verge
  [Step 5] Query: The individual is former President **Donald Trump**.
    -> Loop Detected (Sim: 1.00). Stopping.

[Finalizing]...

Processing Queries:   4%|▍         | 2/50 [05:53<2:24:57, 181.20s/it]

[Processing TSSS Semantic]: Between the report by The Age on October 22, 2023, claiming that Google manipulates Search to maximize ad revenue, and the TechCrunch report on December 15, 2023, alleging that Google "siphons off" news publishers' content, readers, and ad revenue through anticompetitive means, was there consistency in the portrayal of Google's business practices by these news sources?

  [Step 1] Query: **Suggested additional question**

*What specific evidence or examples do The Age (Oct 22 2023) and TechCrunch (Dec 15 2023) cite to support their claims about Google’s manipulation of search results and “siphoning” of news content, and how do those details compare in tone, scope, and implied intent?*
    -> Found New Fact in: The Age
  [Step 2] Query: **Answer to the Main Question**

Yes – the two reports present a **consistent** picture of Google’s business conduct.

| Aspect | The Age (22 Oct 2023) | TechCrunch (15 Dec 2023) |
|--------|----------------------|--------------------------|
| **Core accusation** | Google **manipulates** its own Search results to steer users toward its own products and paid placements, thereby boosting ad revenue. | Google **“siphons off”** news‑publisher content, readers and ad revenue by leveraging its dominant platforms (Search, News, Ads) in ways that disadvantage publishers. |
| **Illustrative example** | A search for “children’s clothing” is automatically replaced with a brand‑specific result (“NIKOLAI‑brand kidswear”), showing direct interference with the user’s query. | Publishers report that Google’s algorithms and the Google News ecosystem prioritize Google‑controlled content and ads, pulling traffic and ad dollars away from the original publishers. |
| **Underlying theme** | **Self‑preferencing** – Google uses its control of the search index to favor its own commercial interests. | **Self‑preferencing & market‑power abuse** – Google uses its control of multiple distribution channels to extract value from third‑party content creators. |
| **Tone** | Critical, framing the behavior as a deliberate, revenue‑driven manipulation of the user experience. | Critical, framing the behavior as anticompetitive “siphoning” that harms the news ecosystem. |

Both outlets therefore **converge on the narrative that Google exploits its dominant position to prioritize its own products and revenue streams at the expense of users and third‑party publishers**. The specific mechanisms they cite differ (search‑query substitution vs. content‑distribution and ad‑revenue diversion), but the overarching portrayal—Google as a self‑servicing, profit‑driven monopoly—is consistent across the two stories.

---

### Proposed Additional Question

**How have regulators and competition authorities in the United States, Europe, and Australia responded to these allegations of search manipulation and news‑publisher “siphoning,” and what potential policy measures are being discussed to curb such practices?**
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: The Age
  [Step 3] Query: **Answer to the Main Question**

Yes – the two reports are consistent in how they portray Google’s business practices.

| Aspect | The Age (22 Oct 2023) | TechCrunch (15 Dec 2023) |
|--------|----------------------|--------------------------|
| **Core accusation** | Google deliberately skews search results (e.g., swapping “children’s clothing” for the brand “NIKOLAI‑brand kidswear”) to broaden the pool of content that can be auctioned to advertisers. | Google “siphons off” news publishers’ content, readers and ad revenue by pulling stories into its own SERP/News widgets and selling the associated ad inventory. |
| **Mechanism cited** | Use of *semantic keyword matching* that makes searches less precise on purpose, inflating ad‑auction volume. | Anticompetitive integration of publisher content into Google‑controlled surfaces, then monetising that traffic with Google‑owned ads. |
| **Underlying motive** | Maximising Google’s ad revenue at the expense of competitors and advertisers who lose precise targeting. | Capturing the value of publishers’ editorial work and audience without sharing the revenue, thereby expanding Google’s ad‑selling monopoly. |
| **Tone** | Critical, emphasizing manipulation of the search algorithm to favor Google’s own ad ecosystem. | Critical, emphasizing extraction of value from third‑party news publishers through “siphoning” tactics. |

Both articles therefore present Google as a platform that **engineers its own traffic and ad‑selling environment** to the detriment of external content creators, advertisers, and, ultimately, users. The specific examples differ (search‑term substitution vs. news‑content aggregation), but the overarching narrative—that Google leverages its dominance to **inflate its ad revenue by reshaping the flow of information**—is the same.

---

### Proposed Additional Question

**How might the alleged practices described by The Age and TechCrunch affect competition in the digital advertising market, and what regulatory responses have been considered or implemented in response to these concerns?**

*This follow‑up question invites a deeper dive into the competitive implications of Google’s tactics and the policy landscape surrounding antitrust scrutiny of big tech platforms.*
    -> [Override] New Terms Detected: {'scrutiny', 'portray', 'inflate', 'articles', 'aggregation', 'auctioned', 'leverages', 'work', 'matching', 'platform', 'this', 'reshaping', 'tactics', 'skews', 'targeting', 'or', 'implemented', 'into', 'sharing', 'response', 'be', 'dominance', 'regulatory', 'semantic', 'landscape', 'external', 'dive', 'big', 'less', 'environment', 'keyword', 'precise', 'implications', 'up', 'motive', 'concerns', 'who', 'advertising', 'broaden', 'extraction', 'swapping', 'algorithm', 'antitrust', 'engineers', 'ultimately', 'competitors', 'auction', 'considered', 'competitive', 'makes', 'monetising', 'inventory', 'inflating', 'cited', 'selling', 'same', 'flow', 'affect', 'deeper', 'information', 'searches', 'integration', 'through', 'capturing', 'term', 'editorial', 'serp', 'described', 'volume', 'detriment', 'follow', 'responses', 'alleged', 'owned', 'been', 'pool', 'advertisers', 'can', 'then', 'without', 'associated', 'mechanism', 'emphasizing', 'digital', 'deliberately', 'use', 'invites', 'widgets', 'might', 'audience', 'surrounding', 'purpose', 'surfaces', 'examples', 'tech', 'expanding', 'lose', 'maximising'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 4] Query: **Answer**

Yes – the two reports are consistent in their portrayal of Google’s business practices. Both The Age (Oct 22 2023) and TechCrunch (Dec 15 2023) present Google as a company that deliberately skews its core platforms to benefit its own advertising ecosystem at the expense of users, competitors, and content creators.

| Aspect | The Age (Oct 22 2023) | TechCrunch (Dec 15 2023) | Consistency |
|--------|----------------------|--------------------------|-------------|
| **Core accusation** | Google “manipulates” Search results to broaden the pool of content that can be auctioned to advertisers. | Google “siphons off” news publishers’ content, readers, and ad revenue through anticompetitive means. | Both describe Google as using its platform to divert value (traffic, ad money) away from third‑party creators toward its own ad business. |
| **Mechanism cited** | Semantic keyword matching that replaces a precise query (“children’s clothing”) with a brand‑specific result (“NIKOLAI‑brand kidswear”), thereby widening the ad inventory. | Integration of Google News and Search that pulls publishers’ articles into Google’s own surfaces, capturing the audience and the ad impressions that would otherwise go to the publishers. | Each story points to a technical/algorithmic tweak that expands Google’s control over the ad‑selling environment. |
| **Impact on third parties** | Increases the number of ad auctions, which can dilute the relevance of results for users and reduce the share of traffic that goes to the original content creators. | Removes readers and ad revenue from the original news sites, leaving them with less traffic and fewer earnings. | Both highlight a loss for external content providers (retail sites in the Age example, news publishers in TechCrunch). |
| **Tone / framing** | Critical – cites critics like Megan Grey who argue the practice is intentional and profit‑driven. | Critical – frames the lawsuit as a response to “anticompetitive” conduct that harms publishers. | Both adopt a skeptical, investigative tone that questions Google’s motives. |
| **Underlying theme** | Google leverages its dominance in search to engineer a larger, more lucrative ad marketplace. | Google leverages its dominance in search and news aggregation to capture the value of publishers’ content. | The central narrative is the same: Google’s market power is being used to re‑route revenue to itself. |

### Why the portrayals line up

1. **Focus on anticompetitive behavior** – Both articles treat Google’s actions as beyond ordinary product optimization; they are presented as strategic moves to “game” the market.
2. **Emphasis on revenue diversion** – Whether it’s ad auctions for retail queries or ad impressions for news articles, the core complaint is that Google is taking money that would otherwise go to other businesses.
3. **Use of concrete examples** – The Age cites a specific search‑term substitution; TechCrunch references the legal complaint of a news publisher. Both concrete cases illustrate the broader allegation of platform abuse.
4. **Reliance on external criticism** – The Age quotes critics like Megan Grey; TechCrunch reports on a lawsuit filed by a publisher. In each case, the criticism comes from parties directly affected by Google’s practices.

### Bottom line

The two reports, though covering different verticals (e‑commerce search vs. news publishing), are consistent in depicting Google as a dominant platform that manipulates its services to maximize its own ad revenue, often at the expense of competitors and content creators. The similarity in framing, the nature of the alleged tactics, and the highlighted consequences all point to a shared critical narrative about Google’s business conduct.
    -> [Override] New Terms Detected: {'portrayal', 'like', 'focus', 'nature', 'parties', 'cites', 'intentional', 'framing', 'away', 'which', 'goes', 'using', 'practice', 'emphasis', 'criticism', 'each', 'relevance', 'businesses', 'cases', 'services', 'treat', 'publishing', 'presented', 'queries', 'share', 'route', 'capture', 'toward', 'result', 'divert', 'dilute', 'megan', 'being', 'itself', 'whether', 'critics', 'consequences', 'concrete', 'impact', 'impressions', 'power', 'reliance', 'other', 'frames', 'taking', 'quotes', 'benefit', 'lawsuit', 'actions', 'describe', 'investigative', 'portrayals', 'comes', 'optimization', 'number', 'leaving', 'abuse', 'verticals', 'skeptical', 'marketplace', 'engineer', 'harms', 'point', 'it', 'over', 'covering', 'them', 'reduce', 'broader', 'otherwise', 'increases', 'directly', 'shared', 'adopt', 'example', 'points', 'driven', 'providers', 'strategic', 'money', 'used', 'pulls', 'diversion', 're', 'questions', 'grey', 'manipulates', 'beyond', 'consistency', 'central', 'dominant', 'means', 'often', 'highlighted', 'theme', 'auctions', 'motives', 'tweak', 'moves', 'their', 'original', 'line', 'commerce', 'technical', 'conduct', 'though', 'allegation', 'would', 'product', 'highlight', 'story', 'bottom', 'about', 'illustrate', 'game', 'depicting', 'lucrative', 'company', 'query', 'more', 'why', 'complaint', 'earnings', 'similarity', 'retail', 'argue', 'larger', 'behavior', 'ordinary', 'go', 'filed', 'expands', 'fewer', 'widening', 'sites', 'maximize', 'replaces', 'affected', 'control', 'algorithmic', 'loss', 'profit', 'removes', 'case', 'legal', 'different', 'all', 'references'}. Ignoring similarity stop.
    -> Found New Fact in: The Age

Processing Queries:   4%|▍         | 2/50 [07:28<2:59:24, 224.25s/it]

KeyboardInterrupt:

In [ ]:
# CSV로 저장 (필요 시)
final_eval_df.to_csv("/content/drive/MyDrive/rag_evaluation_results_oss.csv", index=False, encoding="utf-8-sig")
print("결과가 'rag_evaluation_results_oss.csv'로 저장되었습니다.")

In [4]:
# @title 평가지표
import pandas as pd
import ast
import re
import string
from collections import Counter
# import os
# from google.colab import drive, userdata


# # 1. 구글 드라이브 마운트 (데이터가 드라이브에 있으므로 필수)
# if not os.path.exists('/content/drive'):
#     drive.mount('/content/drive')

# 1. 파일 로드 (경로는 사용자 환경에 맞게 유지)
df = pd.read_csv("/content/drive/MyDrive/rag_evaluation_results_oss.csv", encoding="utf-8-sig")

# ------------------------------------------------------------------
# [Helper] 파싱 함수
# ------------------------------------------------------------------
def parse_list_robust(x):
    if not isinstance(x, str): return []
    try:
        return ast.literal_eval(x)
    except:
        pass
    fixed_str = re.sub(r'\}\s*\{', '}, {', x)
    try:
        return ast.literal_eval(fixed_str)
    except:
        return []

df['evidence_list'] = df['evidence_list'].apply(parse_list_robust)
df['RAG_evidence_list'] = df['RAG_evidence_list'].apply(parse_list_robust)

# ------------------------------------------------------------------
# [Metric 1] Retrieval Metrics (Hit, MRR, MAP)
# ------------------------------------------------------------------
def calculate_retrieval_metrics(row, k=5):
    gold_urls = set([item.get('url') for item in row['evidence_list'] if item.get('url')])
    raw_retrieved_urls = [item.get('url') for item in row['RAG_evidence_list'] if item.get('url')]

    # 중복 제거 (순서 유지)
    retrieved_urls = []
    seen = set()
    for url in raw_retrieved_urls:
        if url not in seen:
            retrieved_urls.append(url)
            seen.add(url)
    retrieved_urls = retrieved_urls[:k]

    # Hit@K
    hit = 1 if not gold_urls.isdisjoint(retrieved_urls) else 0

    # MRR@K
    mrr = 0
    for i, url in enumerate(retrieved_urls):
        if url in gold_urls:
            mrr = 1 / (i + 1)
            break

    # MAP@K
    num_gold = len(gold_urls)
    if num_gold == 0:
        ap = 0
    else:
        hits = 0
        sum_precisions = 0
        for i, url in enumerate(retrieved_urls):
            if url in gold_urls:
                hits += 1
                sum_precisions += hits / (i + 1)
        ap = sum_precisions / num_gold

    return pd.Series([hit, mrr, ap], index=[f'Hit@{k}', f'MRR@{k}', f'MAP@{k}'])

# [Metric 2] Answer Match Accuracy (Exact Match & F1)
def normalize_answer(s):
    """
    평가를 위해 답변 텍스트를 정규화합니다.
    (소문자 변환, 문장부호 제거)
    """

    def white_space_fix(text):
        return ' '.join(text.split())

    def remove_punc(text):
        exclude = set(string.punctuation)
        return ''.join(ch for ch in text if ch not in exclude)

    def lower(text):
        return str(text).lower()

    if not s or pd.isna(s): return ""

    return white_space_fix(remove_punc(lower(s)))

def calculate_qa_metrics(row):
    """
    정답(Answer)과 모델 예측(RAG_Answer)을 비교합니다.
    """
    gold_text = normalize_answer(row['answer'])
    pred_text = normalize_answer(row['RAG_answer'])

    # Exact Match (EM): 완전히 일치하는가? (0 or 1)
    em = 1 if gold_text == pred_text else 0


    return pd.Series([em], index=['Exact Match Accuracy'])

# ------------------------------------------------------------------
# [Execution] 전체 적용 및 저장
# ------------------------------------------------------------------
K_VALUE = 5

# 1. Retrieval Score 계산
retrieval_scores = df.apply(lambda row: calculate_retrieval_metrics(row, k=K_VALUE), axis=1)

# 2. QA Score 계산 (추가된 부분)
qa_scores = df.apply(calculate_qa_metrics, axis=1)

# 3. 전체 데이터프레임 병합
final_df = pd.concat([df, retrieval_scores, qa_scores], axis=1)

# 결과 출력 (평균 점수 확인)
print(f"======== Evaluation Results (K={K_VALUE}) ========")
# 백분율(%)로 변환하여 출력
summary = final_df[[f'Hit@{K_VALUE}', f'MRR@{K_VALUE}', f'MAP@{K_VALUE}', 'Exact Match Accuracy']].mean() * 100
print(summary)

# CSV 저장
save_path = "/content/drive/MyDrive/rag_evaluation_with_all_metrics_oss.csv"
final_df.to_csv(save_path, index=False, encoding="utf-8-sig")
print(f"\n[Done] 결과 파일이 저장되었습니다: {save_path}")

======== Evaluation Results (K=5) ========
Hit@5                   68.000000
MRR@5                   59.166667
MAP@5                   31.291667
Exact Match Accuracy    64.000000
dtype: float64

[Done] 결과 파일이 저장되었습니다: /content/drive/MyDrive/rag_evaluation_with_all_metrics.csv

In [5]:
pd.read_csv("/content/drive/MyDrive/rag_evaluation_with_all_metrics.csv")

,query,evidence_list,RAG_evidence_list,answer,RAG_answer,Hit@5,MRR@5,MAP@5,Exact Match Accuracy
0,"Does the TechCrunch article suggest that ""Peop...","[{'author': 'Sarah Perez', 'category': 'techno...","[{'author': 'Christy Doran', 'category': 'spor...",Yes,Yes,1.0,1.000000,0.500000,1
1,Who is the individual targeted by Attorney Gen...,"[{'author': 'Michael R. Sisak, The Associated ...","[{'author': 'Michael R. Sisak, The Associated ...",Donald Trump,Donald Trump,1.0,1.000000,0.500000,1
2,"Between the report by The Age on October 22, 2...","[{'author': 'Kyle Wiggers', 'category': 'techn...","[{'author': 'Sarah Perez', 'category': 'techno...",Yes,Yes,1.0,1.000000,0.333333,1
3,Who is the individual under 30 who was once co...,"[{'author': 'Elizabeth Lopatto', 'category': '...","[{'author': 'Elizabeth Lopatto', 'category': '...",Sam Bankman-Fried,Sam Bankman-Fried,1.0,1.000000,0.250000,1
4,Does the TechCrunch article report on new hiri...,"[{'author': 'Alyssa Stringer', 'category': 'te...","[{'author': 'Jessica Conditt', 'category': 'te...",no,Yes,1.0,1.000000,0.500000,0
5,Does the TechCrunch article discussing Meta's ...,"[{'author': 'Morgan Sung', 'category': 'techno...","[{'author': 'Morgan Sung', 'category': 'techno...",Yes,Yes,1.0,1.000000,0.500000,1
6,"Which company, according to Eddy Cue, had no v...","[{'author': 'David Pierce', 'category': 'techn...","[{'author': 'Sarah Perez', 'category': 'techno...",Google,Google,1.0,1.000000,0.666667,1
7,Between the article from 'The Independent - Li...,"[{'author': 'Chelsea Ritschel', 'category': 'e...","[{'author': 'Amber Raiken', 'category': 'enter...",Yes,Yes,1.0,1.000000,1.000000,1
8,Considering the information from an article in...,[],[],Insufficient information.,Insufficient information,0.0,0.000000,0.000000,1
9,Does the article from 'The Independent - Life ...,"[{'author': 'Chelsea Ritschel', 'category': 'e...","[{'author': 'Chelsea Ritschel', 'category': 'e...",Yes,Yes,1.0,1.000000,0.500000,1
10,Considering the information from a BBC News ar...,[],[],Insufficient information.,Insufficient information,0.0,0.000000,0.000000,1
11,Who has been considered a prodigy in Silicon V...,"[{'author': ""Matt O'Brien, The Associated Pres...","[{'author': 'Cade Metz, Karen Weise, Nico Gran...",Sam Altman,Sam Altman,1.0,0.500000,0.250000,1
12,"Which company, often covered by The Verge and ...","[{'author': 'David Pierce', 'category': 'techn...","[{'author': 'Mia Sato', 'category': 'technolog...",Google,Google,1.0,1.000000,0.666667,1
13,"Which company, according to articles from Tech...","[{'author': 'Rebecca Bellan', 'category': 'tec...","[{'author': 'Sarah Perez', 'category': 'techno...",Google,Google,1.0,1.000000,0.666667,1
14,Based on an article from The Times and another...,[],[],Insufficient information.,Insufficient information,0.0,0.000000,0.000000,1
15,"What company, which is expected to focus on Ma...","[{'author': 'Kris Holt', 'category': 'technolo...","[{'author': 'Matt Burns', 'category': 'technol...",Apple,Apple,0.0,0.000000,0.000000,1
16,"Which company, covered by both The Verge and E...","[{'author': 'David Pierce', 'category': 'techn...","[{'author': 'Kris Holt', 'category': 'technolo...",Apple,Apple,1.0,1.000000,0.333333,1
17,Did both the report from The Age after Septemb...,"[{'author': 'Colum Dell, Yardbarker', 'categor...","[{'author': 'Kaleigh Werner', 'category': 'ent...",no,Yes After 2023 Travis Kelce,0.0,0.000000,0.000000,0
18,"Which company, defended by Apple for being the...","[{'author': 'David Pierce', 'category': 'techn...","[{'author': 'Sarah Perez', 'category': 'techno...",Google,Google,1.0,1.000000,0.333333,1
19,"Did the performance of ""Nike's Latin America a...","[{'author': None, 'category': 'business', 'fac...","[{'author': 'None', 'category': 'business', 'f...",Agreement,No,1.0,1.000000,0.500000,0
20,After TechCrunch reported on the U.K. Judicial...,"[{'author': 'Alyssa Stringer', 'category': 'te...",[],Consistent,Insufficient information,0.0,0.000000,0.000000,0
21,Between the TechCrunch report on OpenAI's laun...,"[{'author': 'Devin Coldewey', 'category': 'tec...","[{'author': 'Andrew Tarantola', 'category': 't...",Yes,"Yes, After 2023",1.0,0.500000,0.166667,0
22,Considering the information from a BBC article...,[],"[{'author': 'Mirette Magdy, Bloomberg', 'categ...",Insufficient information.,Mali,0.0,0.000000,0.000000,0
23,Does the article from The Verge suggest that t...,"[{'author': 'Sheena Vasani', 'category': 'tech...","[{'author': 'Sheena Vasani', 'category': 'tech...",no,"Yes, Before",1.0,1.000000,0.500000,0
24,Who is the individual implicated in legal proc...,"[{'author': 'Elizabeth Lopatto', 'category': '...","[{'author': 'Paolo Confino', 'category': 'busi...",Sam Bankman-Fried,Sam Bankman-Fried,0.0,0.000000,0.000000,1
25,Did the 'Sporting News' article on Sean Payton...,"[{'author': 'Kyle Irving', 'category': 'sports...",[],no,Insufficient information,0.0,0.000000,0.000000,0
26,Considering the economic strategies discussed ...,[],"[{'author': 'BusinessWorld', 'category': 'busi...",Insufficient information.,Lawrence Wong,0.0,0.000000,0.000000,0
27,Does the Polygon article on 'Spider-Man: Acros...,"[{'author': 'Pete Volk', 'category': 'entertai...","[{'author': 'Grayson Morley', 'category': 'ent...",Yes,Yes,1.0,1.000000,0.500000,1
28,"Which company, recently featured in articles b...","[{'author': 'Mia Sato', 'category': 'technolog...","[{'author': 'Kyle Wiggers', 'category': 'techn...",Google,Google,1.0,1.000000,0.250000,1
29,Has the reporting style regarding live score u...,"[{'author': 'David Suggs', 'category': 'sports...","[{'author': 'Bryan Murphy', 'category': 'sport...",Yes,Yes,1.0,1.000000,1.000000,1
30,Between the TechCrunch report on Google's expe...,"[{'author': 'Sean Hollister', 'category': 'tec...","[{'author': 'Rebecca Bellan', 'category': 'tec...",Yes,Yes,1.0,0.500000,0.166667,1
31,Who is the Silicon Valley prodigy recognized s...,"[{'author': ""Matt O'Brien, The Associated Pres...","[{'author': 'Devin Coldewey', 'category': 'tec...",Sam Altman,Sam Altman,1.0,1.000000,0.750000,1
32,Does the article from Globes English | Israel ...,"[{'author': 'Anat-Daniely Lev', 'category': 'b...","[{'author': 'Mirette Magdy, Bloomberg', 'categ...",no,Yes,1.0,1.000000,0.500000,0
33,Which company is at the center of legal challe...,"[{'author': 'Sean Hollister', 'category': 'tec...","[{'author': 'Sarah Perez', 'category': 'techno...",Google,Google,1.0,1.000000,0.333333,1
34,Do the articles from CBSSports.com and both ar...,"[{'author': 'CBS Sports Staff', 'category': 's...","[{'author': 'Martin Harris', 'category': 'spor...",Yes,Yes,1.0,1.000000,0.500000,1
35,Did the report from The Sydney Morning Herald ...,"[{'author': 'Will Daniel', 'category': 'busine...","[{'author': '', 'category': 'business', 'fact'...",no,Yes After 2023,1.0,0.333333,0.416667,0
36,Does the article from The Verge claiming that ...,"[{'author': 'Elizabeth Lopatto', 'category': '...","[{'author': 'Elizabeth Lopatto', 'category': '...",Yes,Yes,1.0,1.000000,0.333333,1
37,Does the article from 'The Independent - Sport...,"[{'author': 'Richard Jolly', 'category': 'spor...","[{'author': 'Kyle Bonn', 'category': 'sports',...",Yes,No,1.0,0.500000,0.250000,0
38,Considering the information from an article by...,[],"[{'author': 'Jagmeet Singh', 'category': 'tech...",Insufficient information.,Pune,0.0,0.000000,0.000000,0
39,Does the TechCrunch article on Meta's GDPR com...,"[{'author': 'Natasha Lomas', 'category': 'tech...","[{'author': 'Devin Coldewey', 'category': 'tec...",Yes,Yes,0.0,0.000000,0.000000,1
40,Does the Yardbarker article suggest that Travi...,"[{'author': 'Colum Dell, Yardbarker', 'categor...","[{'author': 'Colum Dell, Yardbarker', 'categor...",no,No,1.0,1.000000,0.500000,1
41,Does the TechCrunch article on GPT-4 suggest a...,"[{'author': 'Alyssa Stringer', 'category': 'te...",[],Yes,Insufficient information,0.0,0.000000,0.000000,0
42,Does the Sportskeeda article consider Malik Wi...,"[{'author': 'Nick Igbokwe', 'category': 'sport...","[{'author': 'Nick Igbokwe', 'category': 'sport...",Yes,Yes,1.0,1.000000,0.500000,1
43,Who is the individual whose criminal trial on ...,"[{'author': 'Jacquelyn Melinek', 'category': '...","[{'author': 'Paolo Confino', 'category': 'busi...",Sam Bankman-Fried,Sam Bankman-Fried,1.0,0.250000,0.062500,1
44,Was there no change in the portrayal of Sam Ba...,"[{'author': 'Jacquelyn Melinek', 'category': '...","[{'author': 'Elizabeth Lopatto', 'category': '...",no,Yes,0.0,0.000000,0.000000,0
45,Does 'The Guardian' describe 'the match' as a ...,"[{'author': 'Ed Aarons at Stamford Bridge', 'c...",[{'author': 'Sid Lowe at the Ramón Sánchez Piz...,no,Yes,0.0,0.000000,0.000000,0
46,Who is the individual facing a criminal trial ...,"[{'author': 'Jacquelyn Melinek', 'category': '...","[{'author': 'Elizabeth Lopatto', 'category': '...",Sam Bankman-Fried,Sam Bankman-Fried,0.0,0.000000,0.000000,1
47,Does the TechCrunch article that discusses the...,"[{'author': 'Kyle Wiggers', 'category': 'techn...","[{'author': 'Kyle Wiggers', 'category': 'techn...",Different stages or versions,No,1.0,0.500000,0.250000,0
48,Who is the individual reported by TechCrunch t...,"[{'author': 'Jacquelyn Melinek', 'category': '...","[{'author': 'Ben Weiss', 'category': 'business...",Sam Bankman-Fried,Sam Bankman-Fried,1.0,0.500000,0.166667,1
49,Did the Sporting News publish an article on Mo...,"[{'author': 'Sam Eggleston', 'category': 'spor...","[{'author': 'Sam Eggleston', 'category': 'spor...",no,Yes 21:25 Sporting News,1.0,1.000000,1.000000,0

여기서부터는 코드 실행 x

## 실험 코드

In [ ]:
import os
import torch
import json
import re
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive, userdata
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

# ==============================================================================
# 1. LLM 모델 선택 섹션 (원하는 모델의 주석을 해제하여 사용하세요)
# ==============================================================================

# [Option A] OpenAI (Default)
from langchain_openai import ChatOpenAI
if "OPENAI_API_KEY" not in os.environ:
    os.environ["OPENAI_API_KEY"] = userdata.get('openai')
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0, seed=2026)
print("LLM Selected: OpenAI (GPT-4o-mini)")

# [Option B] Google Gemini
# from langchain_google_genai import ChatGoogleGenerativeAI
# if "GOOGLE_API_KEY" not in os.environ:
#     os.environ["GOOGLE_API_KEY"] = userdata.get('gemini') # Secrets 이름 확인
# llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0,, seed=2026)
# print("LLM Selected: Google Gemini (1.5 Flash)")

# [Option C] OpenRouter (DeepSeek, Claude, Llama etc.)
# from langchain_openai import ChatOpenAI
# if "OPENROUTER_API_KEY" not in os.environ:
#     os.environ["OPENROUTER_API_KEY"] = userdata.get('openrouter') # Secrets 이름 확인
# llm = ChatOpenAI(
#     base_url="https://openrouter.ai/api/v1",
#     api_key=os.environ["openrouter"],
#     model="openai/gpt-oss-120b:free", # 원하는 모델명으로 변경 가능
#     temperature=0,
#     seed=2026
# )
# print("LLM Selected: OpenRouter")


# TSSS (Think Straight, Stop Smart) 핵심 로직


# [핵심 기능] Stop Smart: 쿼리 유사도 계산기
def calculate_similarity(query1, query2):
    # BGE-M3로 임베딩 (GPU 사용)
    emb1 = embedding_model.embed_query(query1)
    emb2 = embedding_model.embed_query(query2)
    # 코사인 유사도 계산
    return cosine_similarity([emb1], [emb2])[0][0]

# [핵심 기능] Think Straight: 논문 Appendix B 프롬프트 생성기
def generate_tsss_prompt(main_question, history_facts):
    prompt = f"To answer the Main Question ({{ {main_question} }}), "
    if history_facts:
        prompt += "using the following facts:\n"
        for fact in history_facts:
            prompt += f"- {{ {fact} }}\n"
    prompt += "\nI propose the following additional question:\nQuestion: "
    return prompt

# # [메인 로직] TSSS 실행 함수
# def run_tsss_pipeline(question, max_steps=5, threshold=0.85):
#     print(f"\n[Processing TSSS]: {question}\n")

#     history_facts = []
#     past_queries = []
#     collected_docs = []

#     for step in range(max_steps):
#         # --- Step 1. 다음 쿼리 생성 ---
#         prompt_text = generate_tsss_prompt(question, history_facts)
#         msg = HumanMessage(content=prompt_text)

#         # LLM 호출
#         next_query = llm.invoke([msg]).content.strip()
#         next_query = next_query.replace('"', '').replace("Question:", "").strip()

#         print(f"  [Step {step+1}] Generated Query: {next_query}")

#         # --- Step 2. 종료 조건 검사 (Stop Smart) ---
#         # A. LLM 종료 신호
#         if "STOP" in next_query or len(next_query) < 3:
#             print("    -> [Terminator]: LLM signaled STOP.")
#             break

#         # B. 유사도 기반 강제 종료
#         is_repetitive = False
#         for past_q in past_queries:
#             sim_score = calculate_similarity(next_query, past_q)
#             if sim_score > threshold:
#                 print(f"    -> [Terminator]: Similarity {sim_score:.2f} > {threshold}. STOPPING loop.")
#                 is_repetitive = True
#                 break

#         if is_repetitive:
#             break

#         past_queries.append(next_query)

#         # --- Step 3. 검색 (Retrieval) ---
#         try:
#             retrieved_docs = vectorstore.similarity_search(next_query, k=5)

#             if not retrieved_docs:
#                 print("    -> No documents found.")
#                 continue

#             top_doc = retrieved_docs[0]
#             collected_docs.append(top_doc)
#             print(f"    -> Retrieved: {top_doc.metadata.get('source', 'Unknown')}")

#             # --- Step 4. 사실 추출 (Fact Generation) ---
#             fact_extraction_prompt = f"""
#             Based on the Context, briefly answer the Sub-Question.
#             Sub-Question: {next_query}
#             Context: {top_doc.page_content}

#             Answer (Fact):
#             """
#             fact_response = llm.invoke([HumanMessage(content=fact_extraction_prompt)]).content.strip()
#             history_facts.append(fact_response)

#         except Exception as e:
#             print(f"    -> Error during search: {e}")
#             break

#     # --- Step 5. 최종 답변 생성 ---
#     print("\n[Final Generation]...")

#     if not history_facts:
#         final_context = "No relevant information found."
#     else:
#         final_context = "\n".join([f"- {fact}" for fact in history_facts])

#     final_prompt = f"""
#     Based on the collected facts below, provide a clear and concise answer to the Main Question.

#     Main Question: {question}

#     Collected Facts:
#     {final_context}

#     Final Answer:
#     """

#     final_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()
#     return final_answer

def extract_verbatim_evidence(query, context):
    """
    LLM에게 요약을 금지하고, 근거가 되는 '원본 문장'을 그대로 발췌하게 함
    """
    prompt = f"""
    Task: Identify the SINGLE sentence in the [Context] that acts as the core evidence for the [Query].

    [Rules]
    1. Output ONLY the raw sentence from the text.
    2. DO NOT paraphrase, summarize, or edit. Copy-paste exactly.
    3. If the answer is not in the text, output "IRRELEVANT".

    [Query]: {query}
    [Context]: {context}

    Extracted Sentence:
    """
    # 팩트 추출용 LLM 호출
    fact = llm.invoke([HumanMessage(content=prompt)]).content.strip().replace('"', '')
    return fact

# ------------------------------------------------------------------
# [Helper 2] 답변 정제기 (Answer Refiner) - 핵심 추가 기능
# ------------------------------------------------------------------
def refine_to_simplest_form(question, raw_answer):
    """
    서술형 답변을 질문 타입에 맞는 단답형(Entity)으로 변환
    """
    prompt = f"""
    You are a "Data Extractor". Convert the [Raw Answer] into the simplest possible format based on the [Question].

    [Rules]
    1. Who -> Output ONLY the Name .
    2. When -> Output ONLY the Date or Year.
    3. Yes/No -> Output ONLY "Yes" or "No".
    4. What/Which -> Output ONLY the Entity name.
    5. REMOVE all filler phrases like "The answer is...", "Based on the context...", periods(.), etc.

    [Question]: {question}
    [Raw Answer]: {raw_answer}

    Simplest Answer:
    """
    refined = llm.invoke([HumanMessage(content=prompt)]).content.strip()
    return refined

# ------------------------------------------------------------------
# [메인 로직] TSSS + 포맷팅 + 정제기
# ------------------------------------------------------------------
def run_tsss_final_formatted(question, max_steps=5, threshold=0.85):
    print(f"\n[Processing TSSS]: {question}\n")

    history_facts = []
    past_queries = []
    evidence_list = []

    for step in range(max_steps):
        # --- Step 1. 다음 쿼리 생성 (Think Straight) ---
        prompt_text = generate_tsss_prompt(question, history_facts)
        next_query = llm.invoke([HumanMessage(content=prompt_text)]).content.strip()
        next_query = next_query.replace('"', '').replace("Question:", "").strip()

        print(f"  [Step {step+1}] Query: {next_query}")

        # --- Step 2. 종료 조건 (Stop Smart) ---
        if "STOP" in next_query or len(next_query) < 3:
            print("    -> LLM Stop Signal.")
            break

        is_repetitive = False
        for past_q in past_queries:
            sim_score = calculate_similarity(next_query, past_q)
            if sim_score > threshold:
                print(f"    -> Loop Detected (Sim: {sim_score:.2f}). Stopping.")
                is_repetitive = True
                break
        if is_repetitive: break
        past_queries.append(next_query)

        # --- Step 3. 검색 ---
        try:
            retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

            # invoke를 쓰면 LangSmith가 "아, 검색을 수행했구나" 하고 문서를 기록함
            retrieved_docs = retriever.invoke(next_query)

            if not retrieved_docs:
                print("    -> No docs found.")
                continue

            top_doc = retrieved_docs[0]

            # --- Step 4. 원문 Fact (Evidence) 추출 ---
            # 여기서 추출한 문장이 최종 evidence_list의 'fact'가 됩니다.
            verbatim_fact = extract_verbatim_evidence(next_query, top_doc.page_content)

            if "IRRELEVANT" in verbatim_fact:
                print("    -> Found doc, but irrelevant content.")
                continue

            print(f"    -> Found Evidence in: {top_doc.metadata.get('source')}")

            # --- Step 5. TSSS 문맥 업데이트 (History) ---
            # 다음 질문 생성을 위한 짧은 요약 (Evidence가 아님)
            short_fact = f"Fact: {verbatim_fact}"
            history_facts.append(short_fact)

            # --- Step 6. Evidence List 구성 ---
            doc_meta = top_doc.metadata
            evidence_list.append({
                    "author": doc_meta.get("author", "unknown"),
                    "category": doc_meta.get("category", "unknown"),
                    "fact": verbatim_fact,
                    "published_at": doc_meta.get("published_at", "unknown"),
                    "source": doc_meta.get("source","unknowmn"),
                    "title": doc_meta.get("original_title", "No Title"),
                    "url": doc_meta.get("url", "")
                })
            break

            # 중복 방지 후 추가
            if verbatim_fact not in [e['fact'] for e in evidence_list]:
                evidence_list.append(evidence_item)

        except Exception as e:
            print(f"    -> Error: {e}")
            break

    # --- Step 7. 최종 답변 생성 및 정제 ---
    print("\n[Finalizing]...")
    if not history_facts:
        final_answer = "N/A"
    else:
        # 1. 서술형 답변 생성 (Raw)
        final_context = "\n".join(history_facts)
        final_prompt = f"""
        Based on the facts below, answer the Question.
        Question: {question}
        Facts: {final_context}
        """
        raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()

        # 2. 답변 정제 (Refinement -> Simplest Form)
        final_answer = refine_to_simplest_form(question, raw_answer)

    # --- Step 8. 최종 JSON 반환 ---
    return {
        "answer": final_answer,
        "evidence_list": evidence_list
    }

LLM Selected: OpenAI (GPT-4o-mini)

In [ ]:
# test
test_q = "Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch, and is accused by prosecutors of committing fraud for personal gain?"
# result = run_tsss_pipeline(test_q)
# print(f"\n======== RESULT ========\n{result}")
result_data = run_tsss_final_formatted(test_q)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS]: Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch, and is accused by prosecutors of committing fraud for personal gain?

  [Step 1] Query: Who is the individual facing legal issues in the cryptocurrency sector, specifically related to allegations of fraud and conspiracy, as highlighted by major tech news outlets?
    -> Found Evidence in: The Verge

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Sam Bankman-Fried",
  "evidence_list": [
    {
      "author": "Elizabeth Lopatto",
      "category": "technology",
      "fact": "Bankman-Fried’s defense can also introduce risks for people who dealt with him.",
      "published_at": "2023-09-28 12:00:00.000000000Z",
      "source": "The Verge",
      "title": "The FTX trial is bigger than Sam Bankman-Fried",
      "url": "https://www.theverge.com/2023/9/28/23893269/ftx-sam-bankman-fried-trial-evidence-crypto"
    }
  ]
}

In [ ]:
# @title 정밀 탐색 추가
import os
import re
import json
import torch
from langsmith import traceable
from langchain_core.messages import HumanMessage
from langchain_chroma import Chroma
from sklearn.metrics.pairwise import cosine_similarity

# ------------------------------------------------------------------
# 1. [Refactored] 언어 중립적 키워드 감지기 (No Regex Hard-coding)
# ------------------------------------------------------------------
def check_new_terms_detected(query1, query2):
    """
    하드코딩된 정규식(대문자 체크)을 제거하고,
    단순 집합(Set) 연산으로 '새로운 의미 있는 단어'가 추가되었는지 감지합니다.
    (영어, 한국어 모두 작동)
    """
    if not query2: return True

    # 1. 전처리: 특수문자 제거 및 소문자화 (언어 중립성 확보)
    def tokenize(text):
        # 글자, 숫자, 한글 등을 제외한 특수문자는 공백으로 치환
        clean_text = re.sub(r'[^\w\s]', ' ', text).lower()
        return set(clean_text.split())

    tokens_new = tokenize(query1)
    tokens_old = tokenize(query2)

    # 2. 불용어(Stopwords) 처리 (선택 사항: 간단한 것만 제외)
    # 문법적 요소(is, the, 은, 는, 이, 가)가 아닌 '실질적 단어' 차이만 봅니다.
    # 여기서는 간단히 길이 2 이상의 단어만 체크합니다.
    diff = {w for w in (tokens_new - tokens_old) if len(w) > 1}

    if diff:
        print(f"    -> [Override] New Terms Detected: {diff}. Ignoring similarity stop.")
        return True
    return False

# ------------------------------------------------------------------
# 2. [Refactored] 프롬프트 일반화 (No Rule-based Hard-coding)
# ------------------------------------------------------------------
def refine_answer_general(question, raw_answer):
    """
    'Who', 'When' 같은 특정 단어 규칙을 제거하고,
    질문의 의도에 맞는 '핵심 엔티티'만 추출하도록 일반화합니다.
    """
    prompt = f"""
    You are a "Core Entity Extractor".
    Extract the specific Value, Name, Date, or Entity that directly answers the [Question] from the [Raw Answer].

    [Rules]
    1. Output ONLY the core entity. No sentences.
    2. Remove all filler words (e.g., "The answer is", "It is").
    3. If multiple entities are required, list them with commas.

    [Question]: {question}
    [Raw Answer]: {raw_answer}

    Core Entity:
    """
    return llm.invoke([HumanMessage(content=prompt)]).content.strip()

def refine_answer_minimalist(question, raw_answer):
    """
    Without asking complex questions, you'll understand the LLM's intent on your own, transforming you into a police officer who best understands the situation.
    """
    prompt = f"""
    Task: Reduce the [Raw Answer] to the absolute minimum logical unit required by the [Question].

    [Guiding Principle]
    1. **Binary Choice:** Output ONLY "Yes" or "No".
    2. **Timing:** Output ONLY the time clause (e.g., "Before", "After 2023").
    3. **Entity:** Output ONLY the name/entity.
    4. **Unknowable:** If the [Raw Answer] indicates the information is missing or cannot be deduced, output EXACTLY "Insufficient information".
    5. **Formatting:** DROP ALL explanations, articles, and punctuation.

    [Input]
    Question: {question}
    Raw Answer: {raw_answer}

    Minimalist Answer:
    """

    # LLM이 스스로 판단해서 최적의 단어를 선택함
    refined = llm.invoke([HumanMessage(content=prompt)]).content.strip()

    # 혹시 모를 마침표 제거
    return refined.rstrip(".")

# ------------------------------------------------------------------
# 3. [Refactored] 메인 파이프라인 (Fully Parametrized)
# ------------------------------------------------------------------
@traceable(name="TSSS_Final_Clean")
def run_tsss_clean(question, max_steps=5, threshold=0.85, top_k=5): # top_k 파라미터화
    print(f"\n[Processing TSSS Clean]: {question}\n")

    history_facts = []
    past_queries = []
    evidence_list = []

    for step in range(max_steps):
        # --- Step 1. 쿼리 생성 ---
        # (기존 generate_tsss_prompt함수 재사용)
        prompt_text = generate_tsss_prompt(question, history_facts)
        next_query = llm.invoke([HumanMessage(content=prompt_text)]).content.strip()
        next_query = next_query.replace('"', '').replace("Question:", "").strip()

        print(f"  [Step {step+1}] Query: {next_query}")

        # --- Step 2. 종료 조건 (유사도 + 신규 단어 체크) ---
        if "STOP" in next_query or len(next_query) < 2:
            print("    -> LLM Stop Signal.")
            break

        is_repetitive = False
        if past_queries:
            last_query = past_queries[-1]
            sim_score = calculate_similarity(next_query, last_query)

            # 유사도가 높아도, 새로운 단어(check_new_terms_detected)가 있으면 진행
            if sim_score > threshold:
                if check_new_terms_detected(next_query, last_query):
                    is_repetitive = False
                else:
                    print(f"    -> Loop Detected (Sim: {sim_score:.2f}). Stopping.")
                    is_repetitive = True

        if is_repetitive: break
        past_queries.append(next_query)

        # --- Step 3. 검색 (파라미터 top_k 사용) ---
        try:
            retriever = vectorstore.as_retriever(search_kwargs={"k": top_k})
            retrieved_docs = retriever.invoke(next_query)

            if not retrieved_docs:
                print("    -> No docs found.")
                continue

            found_valid = False
            for doc in retrieved_docs:
                verbatim_fact = extract_verbatim_evidence(next_query, doc.page_content)

                if "IRRELEVANT" in verbatim_fact: continue

                source_name = doc.metadata.get('source', 'Unknown')
                print(f"    -> Found Evidence in: {source_name}")
                found_valid = True

                history_facts.append(f"Source [{source_name}]: {verbatim_fact}")

                # 메타데이터 안전하게 가져오기 (.get 기본값 활용)
                doc_meta = doc.metadata
                evidence_list.append({
                    "author": doc_meta.get("author", "unknown"),
                    "category": doc_meta.get("category", "unknown"),
                    "fact": verbatim_fact,
                    "published_at": doc_meta.get("published_at", "unknown"),
                    "source": source_name,
                    "title": doc_meta.get("original_title", "No Title"),
                    "url": doc_meta.get("url", "")
                })
                break

            if not found_valid:
                print("    -> Docs retrieved but content irrelevant.")

        except Exception as e:
            print(f"    -> Error: {e}")
            break

    # --- Step 4. 최종 결과 ---
    print("\n[Finalizing]...")
    if not history_facts:
        final_answer = "N/A"
    else:
        final_context = "\n".join(history_facts)
        final_prompt = f"Question: {question}\nFacts: {final_context}\nAnswer:"
        raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()
        final_answer = refine_answer_general(question, raw_answer)

    return {
        "answer": final_answer,
        "evidence_list": evidence_list
    }

# # 실행
# test_q = "Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch?"
# result_data = run_tsss_clean(test_q, top_k=3) # 파라미터로 제어

# print(f"\n======== FINAL JSON OUTPUT ========")
# print(json.dumps(result_data, indent=2, ensure_ascii=False))

In [ ]:
# 실행
test_q = "Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch?"
result_data = run_tsss_clean(test_q, top_k=5) # 파라미터로 제어

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Clean]: Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch?

  [Step 1] Query: Who is the individual facing legal issues in the cryptocurrency sector, specifically related to fraud and conspiracy allegations, as highlighted by The Verge and TechCrunch?
    -> Found Evidence in: The Verge
  [Step 2] Query: Who is Bankman-Fried and what are the implications of his defense strategy for others involved in the cryptocurrency industry?
    -> Found Evidence in: TechCrunch
  [Step 3] Query: Who is Bankman-Fried and what are the specific charges he is facing in the criminal trial?
    -> Found Evidence in: TechCrunch
  [Step 4] Query: What are the specific charges that Bankman-Fried is facing in his criminal trial?
    -> [Override] New Terms Detected: {'that', 'his'}. Ignoring similarity stop.
    -> Found Evidence in: TechCrunch
  [Step 5] Query: What are the specific charges that Bankman-Fried is facing in his criminal trial?
    -> Loop Detected (Sim: 1.00). Stopping.

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Sam Bankman-Fried",
  "evidence_list": [
    {
      "author": "Elizabeth Lopatto",
      "category": "technology",
      "fact": "Bankman-Fried’s defense can also introduce risks for people who dealt with him.",
      "published_at": "2023-09-28 12:00:00.000000000Z",
      "source": "The Verge",
      "title": "The FTX trial is bigger than Sam Bankman-Fried",
      "url": "https://www.theverge.com/2023/9/28/23893269/ftx-sam-bankman-fried-trial-evidence-crypto"
    },
    {
      "author": "Jacquelyn Melinek",
      "category": "technology",
      "fact": "Bankman-Fried, however, maintained his innocence.",
      "published_at": "2023-10-01 14:00:29.000000000Z",
      "source": "TechCrunch",
      "title": "SBF’s trial starts soon, but how did he — and FTX — get here?",
      "url": "https://techcrunch.com/2023/10/01/ftx-lawsuit-timeline/"
    },
    {
      "author": "Jacquelyn Melinek",
      "category": "technology",
      "fact": "In January, Bankman-Fried pleaded not guilty to all counts, which include wire fraud, conspiracy to commit money laundering and conspiracy to misuse customer funds.",
      "published_at": "2023-10-01 14:00:29.000000000Z",
      "source": "TechCrunch",
      "title": "SBF’s trial starts soon, but how did he — and FTX — get here?",
      "url": "https://techcrunch.com/2023/10/01/ftx-lawsuit-timeline/"
    },
    {
      "author": "Jacquelyn Melinek",
      "category": "technology",
      "fact": "In January, Bankman-Fried pleaded not guilty to all counts, which include wire fraud, conspiracy to commit money laundering and conspiracy to misuse customer funds.",
      "published_at": "2023-10-01 14:00:29.000000000Z",
      "source": "TechCrunch",
      "title": "SBF’s trial starts soon, but how did he — and FTX — get here?",
      "url": "https://techcrunch.com/2023/10/01/ftx-lawsuit-timeline/"
    }
  ]
}

In [ ]:
# @title 중복 제거
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

@traceable(name="TSSS_Final_Semantic")
def run_tsss_semantic_dedup(question, max_steps=5, threshold=0.85, top_k=5):
    print(f"\n[Processing TSSS Semantic]: {question}\n")

    history_facts = []
    past_queries = []
    evidence_list = []

    # [New] 수집된 팩트들의 임베딩을 저장할 리스트 (비교용)
    collected_embeddings = []

    for step in range(max_steps):
        # 1. 쿼리 생성
        prompt_text = generate_tsss_prompt(question, history_facts)
        next_query = llm.invoke([HumanMessage(content=prompt_text)]).content.strip()
        next_query = next_query.replace('"', '').replace("Question:", "").strip()

        print(f"  [Step {step+1}] Query: {next_query}")

        # 2. 종료 조건
        if "STOP" in next_query or len(next_query) < 2:
            print("    -> LLM Stop Signal.")
            break

        is_repetitive = False
        if past_queries:
            last_query = past_queries[-1]
            sim_score = calculate_similarity(next_query, last_query)
            if sim_score > threshold:
                if check_new_terms_detected(next_query, last_query):
                    is_repetitive = False
                else:
                    print(f"    -> Loop Detected (Sim: {sim_score:.2f}). Stopping.")
                    is_repetitive = True
        if is_repetitive: break
        past_queries.append(next_query)

        # 3. 검색
        try:
            retriever = vectorstore.as_retriever(search_kwargs={"k": top_k})
            retrieved_docs = retriever.invoke(next_query)

            if not retrieved_docs:
                print("    -> No docs found.")
                continue

            found_valid = False
            for doc in retrieved_docs:
                verbatim_fact = extract_verbatim_evidence(next_query, doc.page_content)
                if "IRRELEVANT" in verbatim_fact: continue

                # ---------------------------------------------------------
                # [New Logic] 의미 기반 중복 제거 (Semantic Deduplication)
                # ---------------------------------------------------------
                # 1. 현재 찾은 팩트를 벡터로 변환
                current_emb = embedding_model.embed_query(verbatim_fact)

                is_duplicate = False

                # 2. 기존 수집된 팩트들과 의미 유사도 비교
                if collected_embeddings:
                    # 전체 리스트와 한번에 비교 (효율적)
                    sims = cosine_similarity([current_emb], collected_embeddings)[0]
                    max_sim = np.max(sims) # 가장 비슷한 문장과의 점수

                    if max_sim > 0.90: # 90% 이상 의미가 같으면 중복 처리
                        print(f"    -> [Skip] Semantically identical content detected (Sim: {max_sim:.2f}).")
                        is_duplicate = True

                if is_duplicate:
                    continue # 다음 문서 확인
                # ---------------------------------------------------------

                source_name = doc.metadata.get('source', 'Unknown')
                print(f"    -> Found New Fact in: {source_name}")
                found_valid = True

                history_facts.append(f"Source [{source_name}]: {verbatim_fact}")

                # 임베딩 저장 (다음 비교를 위해)
                collected_embeddings.append(current_emb)

                doc_meta = doc.metadata
                evidence_list.append({
                    "author": doc_meta.get("author", "unknown"),
                    "category": doc_meta.get("category", "unknown"),
                    "fact": verbatim_fact,
                    "published_at": doc_meta.get("published_at", "unknown"),
                    "source": source_name,
                    "title": doc_meta.get("original_title", "No Title"),
                    "url": doc_meta.get("url", "")
                })
                break

            if not found_valid:
                print("    -> Docs retrieved but content irrelevant or duplicated.")

        except Exception as e:
            print(f"    -> Error: {e}")
            break

    # 4. 최종 결과
    print("\n[Finalizing]...")
    if not history_facts:
        final_answer = "N/A"
    else:
        final_context = "\n".join(history_facts)
        final_prompt = f"Question: {question}\nFacts: {final_context}\nAnswer:"
        raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()
        final_answer = refine_answer_general(question, raw_answer)

    return {
        "answer": final_answer,
        "evidence_list": evidence_list
    }

In [ ]:
# 실행 테스트
test_q = "Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Who is the individual associated with the cryptocurrency industry facing a criminal trial on fraud and conspiracy charges, as reported by both The Verge and TechCrunch?

  [Step 1] Query: Who is the individual facing legal issues in the cryptocurrency sector, specifically related to fraud and conspiracy allegations, as highlighted by The Verge and TechCrunch?
    -> Found New Fact in: The Verge
  [Step 2] Query: Who is Bankman-Fried and what are the implications of his defense strategy for others involved in the cryptocurrency industry?
    -> Found New Fact in: TechCrunch
  [Step 3] Query: Who is Bankman-Fried and what are the specific charges he is facing in the criminal trial?
    -> Found New Fact in: TechCrunch
  [Step 4] Query: What are the specific charges that Bankman-Fried is facing in his criminal trial?
    -> [Override] New Terms Detected: {'that', 'his'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: The Verge
  [Step 5] Query: What are the specific charges that Bankman-Fried is facing in his criminal trial?
    -> Loop Detected (Sim: 1.00). Stopping.

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Sam Bankman-Fried",
  "evidence_list": [
    {
      "author": "Elizabeth Lopatto",
      "category": "technology",
      "fact": "Bankman-Fried’s defense can also introduce risks for people who dealt with him.",
      "published_at": "2023-09-28 12:00:00.000000000Z",
      "source": "The Verge",
      "title": "The FTX trial is bigger than Sam Bankman-Fried",
      "url": "https://www.theverge.com/2023/9/28/23893269/ftx-sam-bankman-fried-trial-evidence-crypto"
    },
    {
      "author": "Jacquelyn Melinek",
      "category": "technology",
      "fact": "Bankman-Fried, however, maintained his innocence.",
      "published_at": "2023-10-01 14:00:29.000000000Z",
      "source": "TechCrunch",
      "title": "SBF’s trial starts soon, but how did he — and FTX — get here?",
      "url": "https://techcrunch.com/2023/10/01/ftx-lawsuit-timeline/"
    },
    {
      "author": "Jacquelyn Melinek",
      "category": "technology",
      "fact": "In January, Bankman-Fried pleaded not guilty to all counts, which include wire fraud, conspiracy to commit money laundering and conspiracy to misuse customer funds.",
      "published_at": "2023-10-01 14:00:29.000000000Z",
      "source": "TechCrunch",
      "title": "SBF’s trial starts soon, but how did he — and FTX — get here?",
      "url": "https://techcrunch.com/2023/10/01/ftx-lawsuit-timeline/"
    },
    {
      "author": "Elizabeth Lopatto",
      "category": "technology",
      "fact": "In the indictment, the prosecutors allege that Bankman-Fried lied to FTX investors.",
      "published_at": "2023-09-28 12:00:00.000000000Z",
      "source": "The Verge",
      "title": "The FTX trial is bigger than Sam Bankman-Fried",
      "url": "https://www.theverge.com/2023/9/28/23893269/ftx-sam-bankman-fried-trial-evidence-crypto"
    }
  ]
}

In [ ]:
# @title 중복 제거
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

@traceable(name="TSSS_Final_Semantic")
def run_tsss_semantic_dedup(question, max_steps=5, threshold=0.85, top_k=5):
    print(f"\n[Processing TSSS Semantic]: {question}\n")

    history_facts = []
    past_queries = []
    evidence_list = []

    # [New] 수집된 팩트들의 임베딩을 저장할 리스트 (비교용)
    collected_embeddings = []

    for step in range(max_steps):
        # 1. 쿼리 생성
        prompt_text = generate_tsss_prompt(question, history_facts)
        next_query = llm.invoke([HumanMessage(content=prompt_text)]).content.strip()
        next_query = next_query.replace('"', '').replace("Question:", "").strip()

        print(f"  [Step {step+1}] Query: {next_query}")

        # 2. 종료 조건
        if "STOP" in next_query or len(next_query) < 2:
            print("    -> LLM Stop Signal.")
            break

        is_repetitive = False
        if past_queries:
            last_query = past_queries[-1]
            sim_score = calculate_similarity(next_query, last_query)
            if sim_score > threshold:
                if check_new_terms_detected(next_query, last_query):
                    is_repetitive = False
                else:
                    print(f"    -> Loop Detected (Sim: {sim_score:.2f}). Stopping.")
                    is_repetitive = True
        if is_repetitive: break
        past_queries.append(next_query)

        # 3. 검색
        try:
            retriever = vectorstore.as_retriever(search_kwargs={"k": top_k})
            retrieved_docs = retriever.invoke(next_query)

            if not retrieved_docs:
                print("    -> No docs found.")
                continue

            found_valid = False
            for doc in retrieved_docs:
                verbatim_fact = extract_verbatim_evidence(next_query, doc.page_content)
                if "IRRELEVANT" in verbatim_fact: continue

                # ---------------------------------------------------------
                # [New Logic] 의미 기반 중복 제거 (Semantic Deduplication)
                # ---------------------------------------------------------
                # 1. 현재 찾은 팩트를 벡터로 변환
                current_emb = embedding_model.embed_query(verbatim_fact)

                is_duplicate = False

                # 2. 기존 수집된 팩트들과 의미 유사도 비교
                if collected_embeddings:
                    # 전체 리스트와 한번에 비교 (효율적)
                    sims = cosine_similarity([current_emb], collected_embeddings)[0]
                    max_sim = np.max(sims) # 가장 비슷한 문장과의 점수

                    if max_sim > 0.90: # 90% 이상 의미가 같으면 중복 처리
                        print(f"    -> [Skip] Semantically identical content detected (Sim: {max_sim:.2f}).")
                        is_duplicate = True

                if is_duplicate:
                    continue # 다음 문서 확인
                # ---------------------------------------------------------

                source_name = doc.metadata.get('source', 'Unknown')
                print(f"    -> Found New Fact in: {source_name}")
                found_valid = True

                history_facts.append(f"Source [{source_name}]: {verbatim_fact}")

                # 임베딩 저장 (다음 비교를 위해)
                collected_embeddings.append(current_emb)

                doc_meta = doc.metadata
                evidence_list.append({
                    "author": doc_meta.get("author", "unknown"),
                    "category": doc_meta.get("category", "unknown"),
                    "fact": verbatim_fact,
                    "published_at": doc_meta.get("published_at", "unknown"),
                    "source": source_name,
                    "title": doc_meta.get("original_title", "No Title"),
                    "url": doc_meta.get("url", "")
                })
                break

            if not found_valid:
                print("    -> Docs retrieved but content irrelevant or duplicated.")

        except Exception as e:
            print(f"    -> Error: {e}")
            break

    # 4. 최종 결과
    print("\n[Finalizing]...")
    if not history_facts:
        final_answer = "N/A"
    else:
        final_context = "\n".join(history_facts)
        final_prompt = f"Question: {question}\nFacts: {final_context}\nAnswer:"
        raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()
        final_answer = refine_answer_general(question, raw_answer)

    return {
        "answer": final_answer,
        "evidence_list": evidence_list
    }

In [ ]:
# 실행 테스트
test_q = "Does the TechCrunch article on Twitch's subscription revenue split policy indicate a different monetization strategy compared to the TechCrunch article on Beeper's plans for Beeper Mini subscriptions?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Does the TechCrunch article on Twitch's subscription revenue split policy indicate a different monetization strategy compared to the TechCrunch article on Beeper's plans for Beeper Mini subscriptions?

  [Step 1] Query: What are the key differences in the monetization strategies outlined in the TechCrunch articles for Twitch's subscription revenue split policy and Beeper's plans for Beeper Mini subscriptions?
    -> Found New Fact in: TechCrunch
  [Step 2] Query: What are the key differences in monetization strategies between Twitch's new subscription revenue split policy and Beeper's approach to its Mini subscriptions?
    -> [Override] New Terms Detected: {'between', 'approach', 'its', 'to', 'new'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 3] Query: What are the key differences in monetization strategies between Twitch's subscription revenue split policy and Beeper's plans for Beeper Mini subscriptions?
    -> [Override] New Terms Detected: {'for', 'plans'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 4] Query: How do the subscription pricing strategies of Twitch and Beeper reflect their overall business models and target audiences?
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 5] Query: How do the subscription revenue models of Twitch and Beeper Mini reflect their respective approaches to monetization and creator support?
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Docs retrieved but content irrelevant or duplicated.

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Twitch, Beeper, 70/30, 50/50, $1.99",
  "evidence_list": [
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "Last year, the company announced that it would end the 70/30 subscription revenue split deal that it had offered select streamers in favor of prioritizing ad revenue.",
      "published_at": "2023-10-26 22:28:10.000000000Z",
      "source": "TechCrunch",
      "title": "Twitch’s money guy talks about the revenue split controversy and its monetization long game",
      "url": "https://techcrunch.com/2023/10/26/twitch-mike-minton-chief-monetization-officer-twitchcon-2023-partner-plus-revenue-split/"
    },
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "The default sub (subscription) revenue split for Partners is 50/50, but select streamers were offered a premium 70/30 deal until last year.",
      "published_at": "2023-09-30 00:13:12.000000000Z",
      "source": "TechCrunch",
      "title": "Kick streamers consider leaving over CEO’s comments in a sex worker ‘prank’ stream",
      "url": "https://techcrunch.com/2023/09/29/kick-streamers-leave-ceo-ice-poseidon-prank-sex-work/"
    },
    {
      "author": "Sarah Perez",
      "category": "technology",
      "fact": "Beeper Mini is competitively priced at $1.99 per month, with a seven-day free trial, compared with $15 per month for the recently acquired competitor Texts.com bought by Automattic.",
      "published_at": "2023-12-05 15:00:57.000000000Z",
      "source": "TechCrunch",
      "title": "Beeper reversed engineered iMessage to bring blue bubble texts to Android users",
      "url": "https://techcrunch.com/2023/12/05/beeper-reversed-engineered-imessage-to-bring-blue-bubble-texts-to-android-users/"
    },
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "One thing we’ve done since the beginning, where we are a leader, is getting people to take their wallets out and support creators through subscriptions, gifting, cheering.",
      "published_at": "2023-10-26 22:28:10.000000000Z",
      "source": "TechCrunch",
      "title": "Twitch’s money guy talks about the revenue split controversy and its monetization long game",
      "url": "https://techcrunch.com/2023/10/26/twitch-mike-minton-chief-monetization-officer-twitchcon-2023-partner-plus-revenue-split/"
    }
  ]
}

In [ ]:
# @title 단답형 대답 추가
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

@traceable(name="TSSS_Final_Semantic")
def run_tsss_semantic_dedup(question, max_steps=5, threshold=0.85, top_k=5):
    print(f"\n[Processing TSSS Semantic]: {question}\n")

    history_facts = []
    past_queries = []
    evidence_list = []

    # [New] 수집된 팩트들의 임베딩을 저장할 리스트 (비교용)
    collected_embeddings = []

    for step in range(max_steps):
        # 1. 쿼리 생성
        prompt_text = generate_tsss_prompt(question, history_facts)
        next_query = llm.invoke([HumanMessage(content=prompt_text)]).content.strip()
        next_query = next_query.replace('"', '').replace("Question:", "").strip()

        print(f"  [Step {step+1}] Query: {next_query}")

        # 2. 종료 조건
        if "STOP" in next_query or len(next_query) < 2:
            print("    -> LLM Stop Signal.")
            break

        is_repetitive = False
        if past_queries:
            last_query = past_queries[-1]
            sim_score = calculate_similarity(next_query, last_query)
            if sim_score > threshold:
                if check_new_terms_detected(next_query, last_query):
                    is_repetitive = False
                else:
                    print(f"    -> Loop Detected (Sim: {sim_score:.2f}). Stopping.")
                    is_repetitive = True
        if is_repetitive: break
        past_queries.append(next_query)

        # 3. 검색
        try:
            retriever = vectorstore.as_retriever(search_kwargs={"k": top_k})
            retrieved_docs = retriever.invoke(next_query)

            if not retrieved_docs:
                print("    -> No docs found.")
                continue

            found_valid = False
            for doc in retrieved_docs:
                verbatim_fact = extract_verbatim_evidence(next_query, doc.page_content)
                if "IRRELEVANT" in verbatim_fact: continue

                # ---------------------------------------------------------
                # [New Logic] 의미 기반 중복 제거 (Semantic Deduplication)
                # ---------------------------------------------------------
                # 1. 현재 찾은 팩트를 벡터로 변환
                current_emb = embedding_model.embed_query(verbatim_fact)

                is_duplicate = False

                # 2. 기존 수집된 팩트들과 의미 유사도 비교
                if collected_embeddings:
                    # 전체 리스트와 한번에 비교 (효율적)
                    sims = cosine_similarity([current_emb], collected_embeddings)[0]
                    max_sim = np.max(sims) # 가장 비슷한 문장과의 점수

                    if max_sim > 0.90: # 90% 이상 의미가 같으면 중복 처리
                        print(f"    -> [Skip] Semantically identical content detected (Sim: {max_sim:.2f}).")
                        is_duplicate = True

                if is_duplicate:
                    continue # 다음 문서 확인
                # ---------------------------------------------------------

                source_name = doc.metadata.get('source', 'Unknown')
                print(f"    -> Found New Fact in: {source_name}")
                found_valid = True

                history_facts.append(f"Source [{source_name}]: {verbatim_fact}")

                # 임베딩 저장 (다음 비교를 위해)
                collected_embeddings.append(current_emb)

                doc_meta = doc.metadata
                evidence_list.append({
                    "author": doc_meta.get("author", "unknown"),
                    "category": doc_meta.get("category", "unknown"),
                    "fact": verbatim_fact,
                    "published_at": doc_meta.get("published_at", "unknown"),
                    "source": source_name,
                    "title": doc_meta.get("original_title", "No Title"),
                    "url": doc_meta.get("url", "")
                })
                break

            if not found_valid:
                print("    -> Docs retrieved but content irrelevant or duplicated.")

        except Exception as e:
            print(f"    -> Error: {e}")
            break

    # 4. 최종 결과
    # print("\n[Finalizing]...")
    # if not history_facts:
    #     final_answer = "N/A"
    # else:
    #     final_context = "\n".join(history_facts)
    #     final_prompt = f"Question: {question}\nFacts: {final_context}\nAnswer:"
    #     raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()
    #     # refine_answer_general -> refine_answer_minimalist
    #     final_answer = refine_answer_minimalist(question, raw_answer)

    # return {
    #     "answer": final_answer,
    #     "evidence_list": evidence_list
    # }
    # ... (run_tsss_semantic_dedup 함수의 마지막 부분) ...

    # 4. 최종 결과 생성 및 후처리
    print("\n[Finalizing]...")
    if not history_facts:
        final_answer = "Insufficient information" # 찾은 팩트가 아예 없으면
    else:
        final_context = "\n".join(history_facts)

        # 서술형 답변 생성
        final_prompt = f"Question: {question}\nFacts: {final_context}\nAnswer:"
        raw_answer = llm.invoke([HumanMessage(content=final_prompt)]).content.strip()

        # 단답형 정제 (여기서 'Insufficient information'이 튀어나올 수 있음)
        final_answer = refine_answer_minimalist(question, raw_answer)

    # 추론 불가면 빈값 반환
    if final_answer == "Insufficient information":
        evidence_list = []  # 리스트 강제 초기화
        print("    -> Result: Insufficient info. Cleared evidence list.")

    return {
        "answer": final_answer,
        "evidence_list": evidence_list
    }

In [ ]:
# 실행 테스트
test_q = "Does the TechCrunch article on Twitch's subscription revenue split policy indicate a different monetization strategy compared to the TechCrunch article on Beeper's plans for Beeper Mini subscriptions?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Does the TechCrunch article on Twitch's subscription revenue split policy indicate a different monetization strategy compared to the TechCrunch article on Beeper's plans for Beeper Mini subscriptions?

  [Step 1] Query: What are the key differences in the monetization strategies outlined in the TechCrunch articles for Twitch's subscription revenue split policy and Beeper's plans for Beeper Mini subscriptions?
    -> Found New Fact in: TechCrunch
  [Step 2] Query: What are the key differences in monetization strategies between Twitch's new subscription revenue split policy and Beeper's approach to its Mini subscriptions?
    -> [Override] New Terms Detected: {'between', 'approach', 'its', 'to', 'new'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 3] Query: What are the key differences in monetization strategies between Twitch's subscription revenue split policy and Beeper's plans for Beeper Mini subscriptions?
    -> [Override] New Terms Detected: {'for', 'plans'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 4] Query: How do the subscription pricing strategies of Twitch and Beeper reflect their overall business models and target audiences?
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: TechCrunch
  [Step 5] Query: How do the subscription revenue models of Twitch and Beeper Mini reflect their respective approaches to monetization and creator support?
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Docs retrieved but content irrelevant or duplicated.

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Yes",
  "evidence_list": [
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "Last year, the company announced that it would end the 70/30 subscription revenue split deal that it had offered select streamers in favor of prioritizing ad revenue.",
      "published_at": "2023-10-26 22:28:10.000000000Z",
      "source": "TechCrunch",
      "title": "Twitch’s money guy talks about the revenue split controversy and its monetization long game",
      "url": "https://techcrunch.com/2023/10/26/twitch-mike-minton-chief-monetization-officer-twitchcon-2023-partner-plus-revenue-split/"
    },
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "The default sub (subscription) revenue split for Partners is 50/50, but select streamers were offered a premium 70/30 deal until last year.",
      "published_at": "2023-09-30 00:13:12.000000000Z",
      "source": "TechCrunch",
      "title": "Kick streamers consider leaving over CEO’s comments in a sex worker ‘prank’ stream",
      "url": "https://techcrunch.com/2023/09/29/kick-streamers-leave-ceo-ice-poseidon-prank-sex-work/"
    },
    {
      "author": "Sarah Perez",
      "category": "technology",
      "fact": "Beeper Mini is competitively priced at $1.99 per month, with a seven-day free trial, compared with $15 per month for the recently acquired competitor Texts.com bought by Automattic.",
      "published_at": "2023-12-05 15:00:57.000000000Z",
      "source": "TechCrunch",
      "title": "Beeper reversed engineered iMessage to bring blue bubble texts to Android users",
      "url": "https://techcrunch.com/2023/12/05/beeper-reversed-engineered-imessage-to-bring-blue-bubble-texts-to-android-users/"
    },
    {
      "author": "Morgan Sung",
      "category": "technology",
      "fact": "One thing we’ve done since the beginning, where we are a leader, is getting people to take their wallets out and support creators through subscriptions, gifting, cheering.",
      "published_at": "2023-10-26 22:28:10.000000000Z",
      "source": "TechCrunch",
      "title": "Twitch’s money guy talks about the revenue split controversy and its monetization long game",
      "url": "https://techcrunch.com/2023/10/26/twitch-mike-minton-chief-monetization-officer-twitchcon-2023-partner-plus-revenue-split/"
    }
  ]
}

In [ ]:
# 실행 테스트
test_q = "Does the Sporting News article suggest that streaming services do not require a subscription for viewing the Cowboys vs. 49ers game, in contrast to the Polygon article's claim about film availability on streaming platforms without a subscription?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Does the Sporting News article suggest that streaming services do not require a subscription for viewing the Cowboys vs. 49ers game, in contrast to the Polygon article's claim about film availability on streaming platforms without a subscription?

  [Step 1] Query: What specific details or statements from the Sporting News article indicate whether streaming services require a subscription for viewing the Cowboys vs. 49ers game, and how do these details compare to the claims made in the Polygon article regarding film availability on streaming platforms?
    -> Found New Fact in: Sporting News
  [Step 2] Query: Does the Sporting News article indicate that viewers can access the Cowboys vs. 49ers game for free through any streaming service, or does it emphasize the need for a subscription or trial?
    -> [Override] New Terms Detected: {'does', 'through', 'any', 'trial', 'service', 'need', 'access', 'emphasize', 'that', 'can', 'free', 'it', 'viewers'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Docs retrieved but content irrelevant or duplicated.
  [Step 3] Query: Does the Sporting News article indicate that viewers can access the Cowboys vs. 49ers game for free through any streaming service, or does it emphasize the need for a subscription or trial?
    -> Loop Detected (Sim: 1.00). Stopping.

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "No",
  "evidence_list": [
    {
      "author": "Dan Treacy",
      "category": "sports",
      "fact": "Fans can also stream the game via Peacock or NBCSports.com with a subscription, along with Fubo, which offers a free trial.",
      "published_at": "2023-10-08 22:47:03.000000000Z",
      "source": "Sporting News",
      "title": "Cowboys vs. 49ers live score, updates, highlights from NFL 'Sunday Night Football' game",
      "url": "https://www.sportingnews.com/us/nfl/news/cowboys-49ers-live-score-highlights-sunday-night-football/e46d8e03c6a948aa82f859c3"
    }
  ]
}

In [ ]:
# 실행 테스트
test_q = "Has the advice provided by Sporting News to bettors regarding the evaluation of betting opportunities and offers involved reading requirements, going with the favored Eagles, and focusing on hype between the reports published on September 28, 2023, and December 18, 2023?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Has the advice provided by Sporting News to bettors regarding the evaluation of betting opportunities and offers involved reading requirements, going with the favored Eagles, and focusing on hype between the reports published on September 28, 2023, and December 18, 2023?

  [Step 1] Query: What specific strategies or criteria does Sporting News recommend for evaluating betting opportunities, particularly in relation to the favored Eagles, and how do these strategies evolve between the reports published on September 28, 2023, and December 18, 2023?
    -> Found New Fact in: Sporting News
  [Step 2] Query: What specific strategies or considerations should bettors keep in mind when evaluating betting opportunities, particularly in relation to favored teams like the Eagles, based on the advice from Sporting News?
    -> [Override] New Terms Detected: {'considerations', 'teams', 'keep', 'bettors', 'should', 'mind', 'advice', 'like', 'when', 'from', 'based'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: Sporting News
  [Step 3] Query: What strategies does Sporting News recommend for bettors when evaluating betting opportunities, particularly regarding the types of bets to prioritize?
    -> Found New Fact in: Sporting News
  [Step 4] Query: What strategies should bettors prioritize when evaluating betting opportunities, according to the advice from Sporting News?
    -> [Override] New Terms Detected: {'according', 'from', 'should', 'advice'}. Ignoring similarity stop.
    -> Found New Fact in: Sporting News
  [Step 5] Query: What strategies does Sporting News recommend for bettors to maximize their potential returns when evaluating betting opportunities?
    -> [Override] New Terms Detected: {'does', 'for', 'their', 'returns', 'potential', 'maximize', 'recommend'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 0.98).
    -> Found New Fact in: Sporting News

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Yes",
  "evidence_list": [
    {
      "author": "Sporting News Betting",
      "category": "sports",
      "fact": "Since you need your moneyline bet to win to claim the $150 in bonus bets, if you’re wagering on tonight’s MNF game, you’ll probably want to go with the favored Eagles.",
      "published_at": "2023-12-18 21:00:03.000000000Z",
      "source": "Sporting News",
      "title": "Best sportsbook bonus offers for NFL Monday Night Football Eagles vs. Seahawks: Claim over $5,000 in bonuses from Bet365, BetMGM, BetRivers, Caesars Sportsbook, DraftKings and FanDuel ",
      "url": "https://www.sportingnews.com/us/betting/news/best-sportsbook-bonus-offers-eagles-seahawks-mnf-bet365-betmgm-betrivers-caesars-draftkings-fanduel%C2%A0/0cac736f90d80f21daafd8a2"
    },
    {
      "author": "Martin Derbyshire",
      "category": "sports",
      "fact": "We wouldn’t recommend using prop bets as your main bet type when building your strategy. Use most of your budget on more stable bet types, such as moneylines, spreads, or totals. Focus only a small percentage of your bankroll on props.",
      "published_at": "2023-11-06 21:23:22.000000000Z",
      "source": "Sporting News",
      "title": "Prop Betting - What is a Prop Bet?",
      "url": "https://www.sportingnews.com/us/betting/news/prop-betting/eca08189bf4e5c58e02bfeda"
    },
    {
      "author": "Sam Eggleston",
      "category": "sports",
      "fact": "For successful Masters betting, it's crucial to consider specific statistics pertinent to the tournament.",
      "published_at": "2023-10-13 21:38:36.000000000Z",
      "source": "Sporting News",
      "title": "Best Golf Betting Sites and Apps - Top Sportsbooks for Golf 2023",
      "url": "https://www.sportingnews.com/us/betting/news/golf-betting-sites/7735c28b8c223b35fb013517"
    },
    {
      "author": "Sam Eggleston",
      "category": "sports",
      "fact": "“By doing this research, you’ll find the best odds for the bets you were already planning on making, which means you can maximize your potential return on your wager.”",
      "published_at": "2023-10-24 22:32:27.000000000Z",
      "source": "Sporting News",
      "title": "MLB Betting Sites & Apps - The Best Baseball Sportsbooks 2023",
      "url": "https://www.sportingnews.com/us/betting/news/mlb-betting-sites/90537abdc639ffc5d57a8c1b"
    },
    {
      "author": "Martin Derbyshire",
      "category": "sports",
      "fact": "Shopping around lets you find the best lines and odds for any bet.",
      "published_at": "2023-11-06 22:21:05.000000000Z",
      "source": "Sporting News",
      "title": "Line Shopping in Sports Betting - How to Find the Best Odds",
      "url": "https://www.sportingnews.com/us/betting/news/line-shopping/0f917db9336b2772ba044571"
    }
  ]
}

In [ ]:
# 실행 테스트
test_q = "Which company, covered by Engadget and Polygon, is set to release an updated gaming hardware with over 300 improvements on November 16, emphasizing a singular performance target for developers?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Which company, covered by Engadget and Polygon, is set to release an updated gaming hardware with over 300 improvements on November 16, emphasizing a singular performance target for developers?

  [Step 1] Query: What specific features or improvements can gamers expect from the updated gaming hardware being released on November 16?
    -> Found New Fact in: Engadget
  [Step 2] Query: What are some of the key features and improvements of the Steam Deck OLED that enhance its performance for gamers?
    -> Found New Fact in: Polygon
  [Step 3] Query: What are the key features and improvements of the Steam Deck OLED that enhance its gaming performance and user experience?
    -> [Override] New Terms Detected: {'gaming', 'experience', 'user'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: Polygon
  [Step 4] Query: What specific features and improvements does the Steam Deck OLED offer compared to its predecessor?
    -> [Override] New Terms Detected: {'does', 'specific', 'predecessor', 'offer', 'compared', 'to'}. Ignoring similarity stop.
    -> Found New Fact in: Engadget
  [Step 5] Query: What are the key features and improvements of the Steam Deck OLED compared to its predecessor?
    -> [Override] New Terms Detected: {'are', 'of', 'key'}. Ignoring similarity stop.
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> [Skip] Semantically identical content detected (Sim: 1.00).
    -> Found New Fact in: Engadget

[Finalizing]...

======== FINAL JSON OUTPUT ========
{
  "answer": "Valve",
  "evidence_list": [
    {
      "author": "Jessica Conditt",
      "category": "technology",
      "fact": "The Steam Deck OLED has a new Wi-Fi 6E module and improved antennas that should enable faster downloads for anyone with a compatible router.",
      "published_at": "2023-11-09 18:00:38.000000000Z",
      "source": "Engadget",
      "title": "Steam Deck OLED review: It's just better",
      "url": "https://www.engadget.com/steam-deck-oled-review-its-just-better-180038030.html?src=rss"
    },
    {
      "author": "Chris Plante",
      "category": "entertainment",
      "fact": "The Steam Deck OLED has longer battery life, faster Wi-Fi, and a stand-alone Bluetooth module.",
      "published_at": "2023-11-09 18:00:00.000000000Z",
      "source": "Polygon",
      "title": "The Steam Deck OLED improves much more than its screen",
      "url": "https://www.polygon.com/reviews/23950861/steam-deck-oled-review-valve-handheld-gaming"
    },
    {
      "author": "Chris Plante",
      "category": "entertainment",
      "fact": "The OLED screen makes for a fancier Steam Deck, but it’s the battery life (and some tweaks throughout the design to carve out more of it) that lets Valve’s new handheld truly deliver on its promise of a portable gaming PC.",
      "published_at": "2023-11-09 18:00:00.000000000Z",
      "source": "Polygon",
      "title": "The Steam Deck OLED improves much more than its screen",
      "url": "https://www.polygon.com/reviews/23950861/steam-deck-oled-review-valve-handheld-gaming"
    },
    {
      "author": "Jessica Conditt,Aaron Souppouris",
      "category": "technology",
      "fact": "As its name suggests, the most noticeable upgrade to the Steam Deck OLED is the display.",
      "published_at": "2023-11-09 18:00:32.000000000Z",
      "source": "Engadget",
      "title": "The Steam Deck OLED arrives November 16 with an improved screen and longer battery life",
      "url": "https://www.engadget.com/the-steam-deck-oled-arrives-november-16-with-an-improved-screen-and-longer-battery-life-180032945.html?src=rss"
    },
    {
      "author": "Jessica Conditt",
      "category": "technology",
      "fact": "The new Steam Deck’s main upgrade is its OLED screen, which replaces the original LCD and, crucially, has native support for HDR and faster frame rates.",
      "published_at": "2023-11-09 18:00:38.000000000Z",
      "source": "Engadget",
      "title": "Steam Deck OLED review: It's just better",
      "url": "https://www.engadget.com/steam-deck-oled-review-its-just-better-180038030.html?src=rss"
    }
  ]
}

In [ ]:
# 실행 테스트
test_q = "Considering the information from an article by The Verge and another by Forbes about Sygic, which letter represents both the first character of the European country where Sygic is headquartered and the last character of the name of Sygic's CEO as mentioned in these articles?"
result_data = run_tsss_semantic_dedup(test_q, top_k=5)

print(f"\n======== FINAL JSON OUTPUT ========")
print(json.dumps(result_data, indent=2, ensure_ascii=False))

[Processing TSSS Semantic]: Considering the information from an article by The Verge and another by Forbes about Sygic, which letter represents both the first character of the European country where Sygic is headquartered and the last character of the name of Sygic's CEO as mentioned in these articles?

  [Step 1] Query: What is the name of the European country where Sygic is headquartered, and who is the CEO of Sygic?
    -> Docs retrieved but content irrelevant or duplicated.
  [Step 2] Query: What is the name of the European country where Sygic is headquartered, and who is the CEO of Sygic?
    -> Loop Detected (Sim: 1.00). Stopping.

[Finalizing]...
    -> Result: Insufficient info. Cleared evidence list.

======== FINAL JSON OUTPUT ========
{
  "answer": "Insufficient information",
  "evidence_list": []
}

In [ ]:
# import pandas as pd

# # 1. DB에 있는 데이터 중 1개만 샘플로 가져오기
# # (limit=1로 설정하여 전체를 다 긁어오지 않고 빠르게 확인)
# sample_data = vectorstore._collection.get(limit=1)

# # 2. 데이터가 있는지 확인
# if len(sample_data['ids']) == 0:
#     print("❌ 데이터베이스가 비어있습니다! 경로를 다시 확인해주세요.")
# else:
#     print("✅ 데이터베이스 연결 성공! 샘플 데이터를 분석합니다.\n")

#     # 3. 메타데이터(Metadata) 구조 확인
#     metadata = sample_data['metadatas'][0]
#     print(f"📌 [Metadata Keys]: {list(metadata.keys())}")
#     print("-" * 50)

#     # 4. 보기 좋게 출력 (Pandas DataFrame 활용)
#     # 실제 값들이 어떻게 들어있는지 예시를 보여줍니다.
#     df = pd.DataFrame([metadata])
#     display(df) # Colab에서는 display()가 표를 예쁘게 보여줍니다.

#     print("\n" + "-" * 50)
#     print("📄 [Document Content (Content Snippet)]:")
#     # 본문 내용은 너무 길 수 있으니 앞부분 200자만 출력
#     content_preview = sample_data['documents'][0][:200]
#     print(f"{content_preview}...")
#     print("-" * 50)

#     # 5. 전체 문서 개수 확인
#     total_count = vectorstore._collection.count()
#     print(f"\n📊 총 저장된 문서 개수: {total_count}개")

✅ 데이터베이스 연결 성공! 샘플 데이터를 분석합니다.

📌 [Metadata Keys]: ['category', 'doc_id', 'author', 'url', 'source', 'chunk_index', 'original_title', 'published_at']
--------------------------------------------------

,category,doc_id,author,url,source,chunk_index,original_title,published_at
0,entertainment,0,None,https://mashable.com/article/cyber-monday-deal...,Mashable,0,200+ of the best deals from Amazon's Cyber Mon...,2023-11-27 08:45:59.000000000Z

--------------------------------------------------
📄 [Document Content (Content Snippet)]:
Title: 200+ of the best deals from Amazon's Cyber Monday sale | Date: 2023-11-27 08:45:59.000000000Z | Source: Mashable

Table of Contents Table of Contents Echo, Fire TV, and Kindle deals Apple deals...
--------------------------------------------------

📊 총 저장된 문서 개수: 2157개